#version 320 es

precision highp uint;
precision highp image2D;
precision highp uimage2D;
precision lowp float;

   

layout (location = 0) uniform ivec2 renderSize;
layout (location = 1) uniform ivec2 colorSize;
layout (location = 2) uniform mat4 prev_to_cur;
layout (location = 3) uniform vec4 jitter;
layout (location = 4) uniform bool  is_revert_z;


layout(binding = 0) uniform sampler2D r_previous_interpolation_source;
layout(binding = 1) uniform sampler2D r_current_interpolation_source;
layout(binding = 2) uniform sampler2D r_previous_depth;
layout(binding = 3) uniform sampler2D r_current_depth;

layout(binding = 0, r32ui) readonly uniform uimage2D r_game_motion_vector_field_x;
layout(binding = 1, rgba8) writeonly uniform image2D rw_output;




const float FFX_FRAMEINTERPOLATION_EPSILON = 1e-3;

const uint MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT = 32u;

// Make sure all bit counts add up to MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT
const uint MOTION_VECTOR_FIELD_VECTOR_COEFFICIENT_BIT_COUNT = 16u;
const uint MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT = 5u;
const uint MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT = 10u;
const uint MOTION_VECTOR_PRIMARY_VECTOR_INDICATION_BIT_COUNT = 1u;
const uint MOTION_VECTOR_FIELD_MOTION_VECTOR_X_BIT_COUNT = 11u;
const uint MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT = 10u;

const uint MOTION_VECTOR_FIELD_MOTION_VECTOR_MASK = 0xFFE00000u; //21bit

const uint MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT = (1U << (MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT - 1u));

const uint PRIORITY_LOW_MAX = (1U << MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT) - 1u;
const uint PRIORITY_HIGH_MAX = (1U << MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT) - 1u;
const uint MOTION_VECTOR_X_MAX = (1U << MOTION_VECTOR_FIELD_MOTION_VECTOR_X_BIT_COUNT) - 1u;
const uint MOTION_VECTOR_Y_MAX = (1U << MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT) - 1u;

const uint MOTION_VECTOR_X_OFFSET = MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT;
const uint PRIORITY_LOW_OFFSET = MOTION_VECTOR_FIELD_VECTOR_COEFFICIENT_BIT_COUNT;
const uint PRIORITY_HIGH_OFFSET = PRIORITY_LOW_OFFSET + MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT;
const uint PRIMARY_VECTOR_INDICATION_OFFSET = PRIORITY_HIGH_OFFSET + MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT;

///////////////////////////////////////////////////////



bool PackedVectorFieldEntryIsPrimary(uint packedEntry) 
{
    return ((packedEntry & MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT) != 0u);
}

uint LoadGameFieldMv(ivec2 iPxSample) 
{
    return imageLoad(r_game_motion_vector_field_x, iPxSample).r;    
}


void StoreFrameinterpolationOutput(in ivec2 iPxPos, in vec4 val)
{
    imageStore(rw_output, iPxPos, val);
}


vec3 LoadCurrentBackbuffer(in ivec2 iPxPos)
{
    return texture(r_current_interpolation_source, vec2(iPxPos) / vec2(renderSize)).rgb;
}


float revertDepth(float depth)
{
    return pow(depth, 1.0 / 10.0);
}
float LinearizeDepth(float depth) 
{
    return pow(depth, 10.0);
    //float z = depth * 2.0 - 1.0;
    //return (2.0 * near * far) / (far + near - z * (far - near));
}

vec2 LinearizeDepth(vec2 depth) 
{
   return pow(depth, vec2(10.0));
}

vec2 LinearizeDepthAndScale(vec2 depth)
{
    //vec2 depth = LinearizeDepth(depth);
    //return depth * 1000.0;
    mediump vec2 near = vec2(1.0); 
    mediump vec2 far = vec2(1000.0);
    mediump vec2 z = depth * vec2(2.0) - vec2(1.0);
    return (2.0 * near * far) / (far + near - z * (far - near));
}


uvec2 getPriorityFactorFromViewSpaceDepth(mediump vec2 fViewSpaceDepthInMeters) 
{
    const vec2 near = vec2(1.0); 
    const vec2 far = vec2( 1000.0);
    const vec2 temp1 = near * far;
    vec2 temp2 = fViewSpaceDepthInMeters *(near - far) + far;
    fViewSpaceDepthInMeters = temp2 / (temp2 + temp1) * 2.0;
    uvec2 uPriorityFactor = uvec2( fViewSpaceDepthInMeters * vec2(PRIORITY_HIGH_MAX));
    if(is_revert_z)
    {
        return uvec2(PRIORITY_HIGH_MAX) - max( uvec2(1u), uPriorityFactor);
    }
    return max( uvec2(1u), uPriorityFactor);
}


void computeFrameinterpolation(ivec2 colorPxPos)
{
    vec3 fColor = vec3(0.0);
    float flag = 1.0;
    {
        vec2 fUv = (vec2(colorPxPos)) / vec2(colorSize);
        ivec2 iPxPos = ivec2(vec2(renderSize) * fUv);
        uint packedGameFieldMv = LoadGameFieldMv(iPxPos);
        
        vec2 fMotionVector = vec2(0.5,0.5);
        if(packedGameFieldMv !=  0u)
        {
            fMotionVector.x = float((packedGameFieldMv >> MOTION_VECTOR_X_OFFSET) & MOTION_VECTOR_X_MAX) / float(MOTION_VECTOR_X_MAX);
            fMotionVector.y = float((packedGameFieldMv) & MOTION_VECTOR_Y_MAX) / float(MOTION_VECTOR_Y_MAX);
        }
        fMotionVector = fMotionVector * vec2(2.0) - vec2(1.0);
        
        vec2 cur_fUv = fUv - fMotionVector; //- jitter.zw;
        if(PackedVectorFieldEntryIsPrimary(packedGameFieldMv))
        {
            fColor = textureLod(r_current_interpolation_source, cur_fUv, 0.0).rgb;
        }
        else
        {   
            
            vec2 prev_fUv = fUv + fMotionVector; // - jitter.xy;
            fColor = textureLod(r_previous_interpolation_source, prev_fUv, 0.0).rgb;
            if((fUv.x < 0.4 || fUv.x > 0.6) || (fUv.y > 0.8))
            {
            }
           else
            {
                mediump float prev_depth = 0.0;
                mediump float cur_depth = 0.0;
                if(packedGameFieldMv !=  0u)
                {
                    uint uHighPriorityFactor = is_revert_z ? (((packedGameFieldMv >> PRIORITY_HIGH_OFFSET)) & PRIORITY_HIGH_MAX): PRIORITY_HIGH_MAX - (((packedGameFieldMv >> PRIORITY_HIGH_OFFSET)) & PRIORITY_HIGH_MAX);
                    prev_depth = textureLod(r_previous_depth, prev_fUv, 0.0).r;
                    cur_depth = textureLod(r_current_depth, cur_fUv, 0.0).r;
                    mediump vec2 prev_device = prev_fUv * vec2(2.0) - vec2(1.0);
                    mediump vec4 cur_clip_pos = prev_to_cur * vec4(prev_device.xy, prev_depth, 1.0);
                    mediump float cur_scree_prj_depth = (cur_clip_pos.z / cur_clip_pos.w);
                    uvec2 utest = getPriorityFactorFromViewSpaceDepth( mediump vec2(cur_scree_prj_depth, cur_depth));
                    ivec2 diff = abs(ivec2(utest) - ivec2(uHighPriorityFactor));
                    if(diff.x > diff.y) // distance to uHighPriorityFactor more less
                    //if(cur_depth > prev_depth)
                    {
                        fColor = textureLod(r_current_interpolation_source, cur_fUv, 0.0).rgb;
                    }
                }
                
                if(abs(prev_depth - cur_depth) < 0.01)
                {
                    float test_depth1 = textureLod(r_previous_depth, fUv, 0.0).r;
                    float test_depth2 = textureLod(r_current_depth, fUv, 0.0).r;
                    float min_depth = min(test_depth1, test_depth2);
                    float max_depth = max(test_depth1, test_depth2);
                    float cur_test_depth = ((prev_depth + cur_depth) / 2.0);
                    if(cur_test_depth < min_depth || max_depth < cur_test_depth)
                    {
                        if(test_depth1 > test_depth2 && is_revert_z == false)
                        {
                            fColor = textureLod(r_previous_interpolation_source, fUv, 0.0).rgb;
                        }
                        else
                        {
                            fColor = textureLod(r_current_interpolation_source, fUv, 0.0).rgb;
                        }
                        
                    }
                }
            }
        }
    }
    /*
    vec2 centerPos = vec2(100, 100);
    float distance = length(centerPos - vec2(colorPxPos));
    if(distance < 30.0)
    {
        fColor = vec3(1.0,0.0,0.0);
    }
    */
    
    StoreFrameinterpolationOutput(colorPxPos, vec4(fColor, flag));
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    ivec2 iPxPos = ivec2(gl_GlobalInvocationID.xy);
    if (all(lessThan(iPxPos.xy, colorSize)))
    {
        computeFrameinterpolation(iPxPos);
    }
    
}
