precision highp int;
precision highp image2D;
precision highp uimage2D;

layout (location = 0) uniform vec2 displaySizeRcp;
layout (location = 1) uniform mat4 inv_project;
layout (location = 2) uniform ivec2 renderSize;
layout (location = 3) uniform bool  is_revert_z;
layout(binding = 0) uniform sampler2D r_current_interpolation_source;
layout(binding = 1, rgba16f) readonly uniform image2D r_dilated_motion_vectors;
layout(binding = 2, rgba16f) readonly uniform image2D r_dilated_depth;
layout(binding = 3, r32ui) uniform uimage2D rw_game_motion_vector_field_x;
layout(binding = 4, r32ui) uniform uimage2D rw_game_motion_vector_field_y;


const float FFX_FRAMEINTERPOLATION_EPSILON = 1e-3;

const uint MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT = 32u;

// Make sure all bit counts add up to MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT
const uint MOTION_VECTOR_FIELD_VECTOR_COEFFICIENT_BIT_COUNT = 16u;
const uint MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT = 5u;
const uint MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT = 10u;
const uint MOTION_VECTOR_PRIMARY_VECTOR_INDICATION_BIT_COUNT = 1u;

const uint MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT = (1U << (MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT - 1u));

const uint PRIORITY_LOW_MAX = (1U << MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT) - 1u;
const uint PRIORITY_HIGH_MAX = (1U << MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT) - 1u;

const uint PRIORITY_LOW_OFFSET = MOTION_VECTOR_FIELD_VECTOR_COEFFICIENT_BIT_COUNT;
const uint PRIORITY_HIGH_OFFSET = PRIORITY_LOW_OFFSET + MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT;
const uint PRIMARY_VECTOR_INDICATION_OFFSET = PRIORITY_HIGH_OFFSET + MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT;

///////////////////////////////////////////////////////

bool PackedVectorFieldEntryIsPrimary(uint packedEntry) {
    return ((packedEntry & MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT) != 0u);
}

struct BilinearSamplingData {
    ivec2 iBasePos;
    ivec2 iOffsets[4];
    float fWeights[4];
};

BilinearSamplingData GetBilinearSamplingData(vec2 fUv, ivec2 iSize) {
    BilinearSamplingData data;

    vec2 fPxSample = (fUv * vec2(iSize)) - vec2(0.5, 0.5);
    data.iBasePos = ivec2(floor(fPxSample));
    vec2 fPxFrac = fract(fPxSample);

    data.iOffsets[0] = ivec2(0, 0);
    data.iOffsets[1] = ivec2(1, 0);
    data.iOffsets[2] = ivec2(0, 1);
    data.iOffsets[3] = ivec2(1, 1);

    data.fWeights[0] = (1.0 - fPxFrac.x) * (1.0 - fPxFrac.y);
    data.fWeights[1] = fPxFrac.x * (1.0 - fPxFrac.y);
    data.fWeights[2] = (1.0 - fPxFrac.x) * fPxFrac.y;
    data.fWeights[3] = fPxFrac.x * fPxFrac.y;

    return data;
}

bool IsUvInside(vec2 fUv) 
{
    return (fUv.x > 0.0 && fUv.x < 1.0) && (fUv.y > 0.0 && fUv.y < 1.0);
}

vec4 MinDividedByMax(vec4 v0, vec4 v1) 
{
    vec4 m = max(v0, v1);
    return min(v0, v1) / m ;
}

uvec4 PackVectorFieldPriorityFactor(uvec4 bIsPrimary, uvec4 uHighPriorityFactor, uvec4 uLowPriorityFactor)
{
     uvec4 uPriority =
        (bIsPrimary * MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT) |
        ((uHighPriorityFactor & PRIORITY_HIGH_MAX) << PRIORITY_HIGH_OFFSET) |
        ((uLowPriorityFactor & PRIORITY_LOW_MAX) << PRIORITY_LOW_OFFSET);
    return uPriority;
}

uvec2 PackVectorFieldEntries(uint bIsPrimary, uint uHighPriorityFactor, uint uLowPriorityFactor, vec2 fMotionVector) 
{
    uint uPriority =
        (uint(bIsPrimary) * MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT) |
        ((uHighPriorityFactor & PRIORITY_HIGH_MAX) << PRIORITY_HIGH_OFFSET) |
        ((uLowPriorityFactor & PRIORITY_LOW_MAX) << PRIORITY_LOW_OFFSET);

    uint packedX = uPriority | packHalf2x16(vec2(fMotionVector.x, 0.0));
    uint packedY = uPriority | packHalf2x16(vec2(fMotionVector.y, 0.0));

    return uvec2(packedX, packedY);
}

uvec2 PackVectorFieldEntries(uint uPriority, vec3 final_color)
{
    uvec3 color_rgb = uvec3(final_color * 255.0);
    uint packed_rg_color = uint(color_rgb.r) | (uint(color_rgb.g) << 8u);
    uint packed_b_color = uint(color_rgb.b);
    uint packedX = uPriority | packed_rg_color;
    uint packedY = uPriority | packed_b_color;
    return uvec2(packedX, packedY);
}

uvec2 PackVectorFieldEntries(uint uPriority, vec2 fMotionVector)
{
    uint packedX = uPriority | packHalf2x16(vec2(fMotionVector.x, 0.0));
    uint packedY = uPriority | packHalf2x16(vec2(fMotionVector.y, 0.0));
    return uvec2(packedX, packedY);
}



vec4 LoadDilatedMotionVector(ivec2 iPxPos) 
{
    return imageLoad(r_dilated_motion_vectors, iPxPos);
}


vec4 LoadDilatedDepth(ivec2 iPxPos) 
{
    return imageLoad(r_dilated_depth, iPxPos);
}

vec3 SampleCurrentBackbuffer(vec2 fUv) 
{
    return texture(r_current_interpolation_source, fUv).xyz;
}

float ConvertFromDeviceDepthToViewSpaceT(float fDeviceDepth) 
{
    vec4 view_pos = inv_project * vec4(0, 0, 2.0*fDeviceDepth - 1.0, 1.0);
    view_pos = view_pos / view_pos.w;
    return view_pos.z * -1.0;
}

vec4 ConvertFromDeviceDepthToViewSpace(vec4 fDeviceDepth) 
{
    vec4 result;
    result.r = ConvertFromDeviceDepthToViewSpaceT(fDeviceDepth.r);
    result.g = ConvertFromDeviceDepthToViewSpaceT(fDeviceDepth.g);
    result.b = ConvertFromDeviceDepthToViewSpaceT(fDeviceDepth.b);
    result.a = ConvertFromDeviceDepthToViewSpaceT(fDeviceDepth.a);
    return result;
}


float LinearizeDepth(float depth) 
{
    return pow(depth, 10.0);
    //float z = depth * 2.0 - 1.0;
    //return (2.0 * near * far) / (far + near - z * (far - near));
}

float LinearizeDepthAndScale(float depth)
{
    //float depth = LinearizeDepth(depth);
    //return depth * 1000.0;
    float near = 1.0; 
    float far = 1000.0;
    float z = depth * 2.0 - 1.0;
    return (2.0 * near * far) / (far + near - z * (far - near));
}

vec4 LinearizeDepthAndScale(vec4 depth)
{
    depth.x = LinearizeDepthAndScale(depth.x);
    depth.y = LinearizeDepthAndScale(depth.y);
    depth.z = LinearizeDepthAndScale(depth.z);
    depth.w = LinearizeDepthAndScale(depth.w);
    return depth;
}

uvec4 getPriorityFactorFromViewSpaceDepth(vec4 fViewSpaceDepthInMeters) 
{
    fViewSpaceDepthInMeters = pow(LinearizeDepthAndScale(fViewSpaceDepthInMeters), vec4(0.33));

    uvec4 uPriorityFactor = uvec4(vec4(1.0 - (fViewSpaceDepthInMeters * (1.0 / (1.0 + fViewSpaceDepthInMeters)))) * float(PRIORITY_HIGH_MAX));
    if(is_revert_z)
    {
        return uvec4(PRIORITY_HIGH_MAX) - max( uvec4(1u), uPriorityFactor);
    }  
    return max( uvec4(1u), uPriorityFactor);
}

void UpdateGameMotionVectorField(in ivec2 iPxPos, in uvec2 packedVector) 
{
    imageAtomicMax(rw_game_motion_vector_field_x, iPxPos, packedVector.x);
    imageAtomicMax(rw_game_motion_vector_field_y, iPxPos, packedVector.y);
}
bool IsOnScreen(ivec2 pos, ivec2 size)
{
    return all( lessThan(ivec2(pos), ivec2(size)));
}




uint UpdateGameMotionVectorFieldEx(in ivec2 iPxPos, in uvec2 packedVector) 
{
    uint uPreviousValueX = 0u;
    uint uPreviousValueY = 0u;
    uPreviousValueX = imageAtomicMax(rw_game_motion_vector_field_x, iPxPos, packedVector.x);
    uPreviousValueY = imageAtomicMax(rw_game_motion_vector_field_y, iPxPos, packedVector.y);
    return max(uPreviousValueX, uPreviousValueY);
}
void FillTheGameMotionVectorHole(vec2 currentUV,  vec2 fMotionVectorHalf, vec2 fGameMotionVector, uint uHighPriorityFactorPrimary)
{   
     vec2 frenderSize = vec2(renderSize);
     bool bWriteSecondaryVectors = length(fMotionVectorHalf * frenderSize) > FFX_FRAMEINTERPOLATION_EPSILON;
    if (bWriteSecondaryVectors) 
    {
        bool bWriteSecondary = true;
        uint uNumPrimaryHits = 0u;
        float fSecondaryStepScale = length(1.0 / frenderSize);
        vec2 fStepMv = normalize(fGameMotionVector);
        float fBreakDist = min(length(fMotionVectorHalf), length(vec2(0.5, 0.5)));
        vec2 fInterpolatedLocationUv = currentUV + fMotionVectorHalf;
        for (float fMvScale = fSecondaryStepScale; fMvScale <= fBreakDist && bWriteSecondary; fMvScale += fSecondaryStepScale) 
        {
            vec2 fSecondaryLocationUv = fInterpolatedLocationUv - fStepMv * fMvScale;
            BilinearSamplingData bilinearInfo = GetBilinearSamplingData(fSecondaryLocationUv, renderSize);

            uint uHighPriorityFactorSecondary = max(1u, PRIORITY_HIGH_MAX - (uHighPriorityFactorPrimary));

            vec2 fToCenter = normalize(vec2(0.5, 0.5) - fSecondaryLocationUv);
            uint uLowPriorityFactor = uint(max(0.0, dot(fToCenter, fStepMv)) * float(PRIORITY_LOW_MAX)) ;
            uvec2 packedVectorSecondary = PackVectorFieldEntries(0u, uHighPriorityFactorSecondary, uLowPriorityFactor, fMotionVectorHalf);

            ivec2 iSamplePos = bilinearInfo.iBasePos;

            bWriteSecondary = bWriteSecondary && IsOnScreen(iSamplePos, renderSize);

            if (bWriteSecondary) 
            {
                uint uExistingVectorFieldEntry = UpdateGameMotionVectorFieldEx(iSamplePos, packedVectorSecondary);

                uNumPrimaryHits += uint(PackedVectorFieldEntryIsPrimary(uExistingVectorFieldEntry));
                bWriteSecondary =  bWriteSecondary && (uNumPrimaryHits <= 3u);
            }
        }
    }
}

vec2 offset_array[3] = vec2[3](vec2(0.0, 1.0), vec2(1.0, 1.0), vec2(1.0, 0.0));
vec3 lum_weight = vec3(0.299, 0.587, 0.114);
void computeGameFieldMvs(ivec2 iPxPos) 
{
    ivec2 fGameMotionVector1Coord = ivec2(iPxPos.x, iPxPos.y * 2); 
    ivec2 fGameMotionVector2Coord = ivec2(iPxPos.x, iPxPos.y * 2 + 1);
    
    mediump vec4 fGameMotionVector1 = LoadDilatedMotionVector(fGameMotionVector1Coord);
    mediump vec4 fGameMotionVector2 = LoadDilatedMotionVector(fGameMotionVector2Coord);
   
    vec4 fViewSpaceDepth = LoadDilatedDepth(iPxPos);
    
    vec4 tempInv = vec4(displaySizeRcp, displaySizeRcp);
    vec2 temp = vec2(iPxPos * 2);
    vec4 sample_uv1 = vec4(temp  , temp + offset_array[0]) * tempInv;
    vec4 sample_uv2 = vec4(temp + offset_array[1], temp + offset_array[2]) * tempInv;
    uvec4 uHighPriorityFactorPrimary = getPriorityFactorFromViewSpaceDepth(fViewSpaceDepth);
    uvec4 uLowPriorityFactor = uvec4(0u, 0u, 0u, 0u) ;
     uvec4 uPriority = PackVectorFieldPriorityFactor(uvec4(1), uHighPriorityFactorPrimary, uLowPriorityFactor); 
    {
        vec4 fInterpolatedLocationUv1 = sample_uv1 + fGameMotionVector1 * 0.5;
        vec4 halfMotionVector = fGameMotionVector1 * 0.5;
        
        bool hold_thr = false;
        uvec2 packedVectorPrimary = PackVectorFieldEntries(uPriority.r, halfMotionVector.xy);
        BilinearSamplingData bilinearInfo = GetBilinearSamplingData(fInterpolatedLocationUv1.xy, renderSize);
        
        //if(is_movable_obj.x == hold_thr)
        {
            UpdateGameMotionVectorField(bilinearInfo.iBasePos, packedVectorPrimary);
            //FillTheGameMotionVectorHole(sample_uv1.xy, fGameMotionVector1.xy * 0.5, fGameMotionVector1.xy, uHighPriorityFactorPrimary.x);
        }
        


        packedVectorPrimary = PackVectorFieldEntries(uPriority.g, halfMotionVector.zw);
        bilinearInfo = GetBilinearSamplingData(fInterpolatedLocationUv1.zw, renderSize);
        
        //if(is_movable_obj.y == hold_thr)
        {
            UpdateGameMotionVectorField(bilinearInfo.iBasePos, packedVectorPrimary);
            //FillTheGameMotionVectorHole(sample_uv1.zw, fGameMotionVector1.zw * 0.5, fGameMotionVector1.xw, uHighPriorityFactorPrimary.y);
        }
        


        vec4 fInterpolatedLocationUv2 = sample_uv2 + fGameMotionVector2 * 0.5;
        halfMotionVector = fGameMotionVector2 * 0.5;
        packedVectorPrimary = PackVectorFieldEntries(uPriority.b, halfMotionVector.xy);
        bilinearInfo = GetBilinearSamplingData(fInterpolatedLocationUv2.xy, renderSize);
        
        //if(is_movable_obj.z == hold_thr)
        {
            UpdateGameMotionVectorField(bilinearInfo.iBasePos, packedVectorPrimary);
            //FillTheGameMotionVectorHole(sample_uv2.xy, fGameMotionVector2.xy * 0.5, fGameMotionVector2.xy, uHighPriorityFactorPrimary.z);
        }
        

        packedVectorPrimary = PackVectorFieldEntries(uPriority.a, halfMotionVector.zw);
        bilinearInfo = GetBilinearSamplingData(fInterpolatedLocationUv2.zw, renderSize);
        
        //if(is_movable_obj.w == hold_thr)
        {
            UpdateGameMotionVectorField(bilinearInfo.iBasePos, packedVectorPrimary);
            //FillTheGameMotionVectorHole(sample_uv2.zw, fGameMotionVector2.zw * 0.5, fGameMotionVector2.zw, uHighPriorityFactorPrimary.w);
        }
      
    }
}

layout(local_size_x = 16, local_size_y = 16) in;
void main() 
{
    ivec2 iPxPos = ivec2(gl_GlobalInvocationID.xy);
    if (all(lessThan(iPxPos.xy, renderSize)))
    {
        computeGameFieldMvs(iPxPos);
    }
    
}
