
precision highp int;

precision highp image2D;
#ifdef Qual_VENDOR
precision highp uint;
precision highp uimage2D;
#else
precision highp uimage2D;
#endif
precision highp float;


layout (location = 0) uniform vec2 inv_renderSize;
layout (location = 1) uniform mat4 transform;
layout (location = 2) uniform ivec2 renderSize;
layout (location = 3) uniform bool  is_revert_z;

layout( binding = 0) uniform sampler2D r_input_depth;
#ifdef ARM_VENDOR
    layout(binding = 1) uniform sampler2D r_input_motion_vectors;
#else
    layout(binding = 0, rgba16f) readonly uniform image2D r_input_motion_vectors;
#endif

layout(binding = 1, r32ui) uniform uimage2D rw_game_motion_vector_field_x;




const float FFX_FRAMEINTERPOLATION_EPSILON = 1e-3;

const uint MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT = 32u;

// Make sure all bit counts add up to MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT
const uint MOTION_VECTOR_FIELD_VECTOR_COEFFICIENT_BIT_COUNT = 16u;
const uint MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT = 5u;
const uint MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT = 10u;
const uint MOTION_VECTOR_PRIMARY_VECTOR_INDICATION_BIT_COUNT = 1u;
const uint MOTION_VECTOR_FIELD_MOTION_VECTOR_X_BIT_COUNT = 10u;
const uint MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT = 9u;

const uint MOTION_VECTOR_FIELD_MOTION_VECTOR_MASK = 0xFFE00000u; //21bit

const uint MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT = (1U << (MOTION_VECTOR_FIELD_ENTRY_BIT_COUNT - 1u));
const uint PRIORITY_LOW_MAX = (1U << MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT) - 1u;
const uint PRIORITY_HIGH_MAX = (1U << MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT) - 1u;
const uint MOTION_VECTOR_X_MAX = (1U << MOTION_VECTOR_FIELD_MOTION_VECTOR_X_BIT_COUNT) - 1u;
const uint MOTION_VECTOR_Y_MAX = (1U << MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT) - 1u;
const highp float INV_MOTION_VECTOR_X_MAX = 1.0 / float(MOTION_VECTOR_X_MAX);
const highp float INV_MOTION_VECTOR_Y_MAX = 1.0 / float(MOTION_VECTOR_Y_MAX);
const highp float MOTION_VECTOR_X_MAX_F = float(MOTION_VECTOR_X_MAX);
const highp float MOTION_VECTOR_Y_MAX_F = float(MOTION_VECTOR_Y_MAX);

const uint MOTION_VECTOR_X_OFFSET = MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT + 1U;
const uint PRIORITY_LOW_OFFSET = MOTION_VECTOR_FIELD_VECTOR_COEFFICIENT_BIT_COUNT;
const uint PRIORITY_HIGH_OFFSET = PRIORITY_LOW_OFFSET + MOTION_VECTOR_FIELD_PRIORITY_LOW_BIT_COUNT;
const uint PRIMARY_VECTOR_INDICATION_OFFSET = PRIORITY_HIGH_OFFSET + MOTION_VECTOR_FIELD_PRIORITY_HIGH_BIT_COUNT;

///////////////////////////////////////////////////////

bool PackedVectorFieldEntryIsPrimary(uint packedEntry) {
    return ((packedEntry & MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT) != 0u);
}

struct BilinearSamplingData {
    ivec2 iBasePos;
    ivec2 iOffsets[4];
    float fWeights[4];
};

BilinearSamplingData GetBilinearSamplingData(vec2 fUv, ivec2 iSize) {
    BilinearSamplingData data;

    vec2 fPxSample = (fUv * vec2(iSize));
    data.iBasePos = ivec2(floor(fPxSample));
    vec2 fPxFrac = fract(fPxSample);

    data.iOffsets[0] = ivec2(0, 0);
    data.iOffsets[1] = ivec2(1, 0);
    data.iOffsets[2] = ivec2(0, 1);
    data.iOffsets[3] = ivec2(1, 1);

    data.fWeights[0] = (1.0 - fPxFrac.x) * (1.0 - fPxFrac.y);
    data.fWeights[1] = fPxFrac.x * (1.0 - fPxFrac.y);
    data.fWeights[2] = (1.0 - fPxFrac.x) * fPxFrac.y;
    data.fWeights[3] = fPxFrac.x * fPxFrac.y;

    return data;
}

bool IsUvInside(vec2 fUv) 
{
    return (fUv.x > 0.0 && fUv.x < 1.0) && (fUv.y > 0.0 && fUv.y < 1.0);
}

vec4 MinDividedByMax(vec4 v0, vec4 v1) 
{
    vec4 m = max(v0, v1);
    return min(v0, v1) / m ;
}

uint PackVectorFieldPriorityFactor(uint bIsPrimary, uint uHighPriorityFactor,uint uLowPriorityFactor)
{
    highp uint uPriority =
        (bIsPrimary * MOTION_VECTOR_FIELD_PRIMARY_VECTOR_INDICATION_BIT) |
        ((uHighPriorityFactor & PRIORITY_HIGH_MAX) << PRIORITY_HIGH_OFFSET) |
        ((uLowPriorityFactor & PRIORITY_LOW_MAX) << PRIORITY_LOW_OFFSET);
    return uPriority;
}

uint PackVectorFieldEntries(uint uPriority, vec2 fMotionVector)
{
    vec2 all_sign = sign(fMotionVector.xy);
    fMotionVector = fMotionVector * all_sign;
    uPriority = uPriority & MOTION_VECTOR_FIELD_MOTION_VECTOR_MASK;
    highp uint packedX = uint(fMotionVector.x * MOTION_VECTOR_X_MAX_F);
    packedX = packedX | ((all_sign.x > 0.0) ? (1U << MOTION_VECTOR_FIELD_MOTION_VECTOR_X_BIT_COUNT) : 0U); 
    highp uint packedY = uint(fMotionVector.y * MOTION_VECTOR_Y_MAX_F);
    packedY = packedY | ((all_sign.y > 0.0) ? (1U << MOTION_VECTOR_FIELD_MOTION_VECTOR_Y_BIT_COUNT) : 0U);
    uPriority = uPriority | (packedX << MOTION_VECTOR_X_OFFSET) | (packedY);
    return uPriority;
}


uint PackVectorFieldEntries_Y(uint uPriority, vec2 fMotionVector)
{
    fMotionVector.xy = (fMotionVector + vec2(1.0)) * vec2(0.5);
    //fMotionVector.xy = pow(fMotionVector.xy, vec2(1.0/2.0));
    uPriority = uPriority & MOTION_VECTOR_FIELD_MOTION_VECTOR_MASK;
    uint packedX = (MOTION_VECTOR_X_MAX - 1u);
    uint packedY = uint(fMotionVector.y * float(MOTION_VECTOR_Y_MAX));
    uPriority = uPriority | (packedX << MOTION_VECTOR_X_OFFSET) | (packedY);
    return uPriority;
}

float LinearizeDepth(float depth) 
{
    return pow(depth, 10.0);
    //float z = depth * 2.0 - 1.0;
    //return (2.0 * near * far) / (far + near - z * (far - near));
}

float LinearizeDepthAndScale(float depth)
{
    const float near = 1.0; 
    const float far = 1000.0;
    const float temp1 = (2.0 * near * far);
    const float temp2 =  far + near;
    const float temp3 = (far - near);
    float z = depth * 2.0 - 1.0;
    return temp1 / (temp2 - z * temp3);
}

uint getPriorityFactorFromViewSpaceDepth(float fViewSpaceDepthInMeters) 
{
    //fViewSpaceDepthInMeters = pow(LinearizeDepthAndScale(fViewSpaceDepthInMeters), (0.33));

    //fViewSpaceDepthInMeters = LinearizeDepthAndScale(fViewSpaceDepthInMeters);
    //uint uPriorityFactor = uint(float(1.0 - (fViewSpaceDepthInMeters * (1.0 / (1.0 + fViewSpaceDepthInMeters)))) * float(PRIORITY_HIGH_MAX));
    
    const float near = 1.0; 
    const float far = 1000.0;
    const float temp1 = near * far;
    float temp2 = fViewSpaceDepthInMeters *(near - far) + far;
    fViewSpaceDepthInMeters = temp2 / (temp2 + temp1)* 2.0;
    uint uPriorityFactor = uint( fViewSpaceDepthInMeters * float(PRIORITY_HIGH_MAX));
    if(is_revert_z)
    {
        return PRIORITY_HIGH_MAX - max( uint(1u), uPriorityFactor);
    }    
    return max( uint(1u), uPriorityFactor);
}

void UpdateGameMotionVectorField(in ivec2 iPxPos, in uint packedVector) 
{
    imageAtomicMax(rw_game_motion_vector_field_x, iPxPos, packedVector);
}


bool IsOnScreen(ivec2 pos, ivec2 size)
{
    return all( lessThan(ivec2(pos), ivec2(size)));
}

float LoadInputDepth(ivec2 iPxPos) 
{
    vec2 uv = (vec2(iPxPos.xy)) * inv_renderSize;
    return textureLod(r_input_depth, uv, 0.0).r;
}

vec3 LoadMotionVector(ivec2 iPxDilatedMotionVectorPos)
{
#ifdef ARM_VENDOR
    vec2 uv = (vec2(iPxDilatedMotionVectorPos.xy)+ vec2(0.5, 0.5)) * inv_renderSize;
    vec3 srcMotionVector = textureLod(r_input_motion_vectors, uv, 0.0).rgb;
#else
    vec3 srcMotionVector = imageLoad(r_input_motion_vectors, iPxDilatedMotionVectorPos).rgb;
#endif
    return srcMotionVector;
}

vec2 LoadInputMotionVector(ivec2 iPxDilatedMotionVectorPos , float depthZ, inout bool is_movable_obj) 
{
    is_movable_obj = false;
    if (all(lessThan(iPxDilatedMotionVectorPos.xy, renderSize))  && all(greaterThan(iPxDilatedMotionVectorPos.xy, ivec2(0,0))))
    {
        vec3 srcMotionVector = LoadMotionVector(iPxDilatedMotionVectorPos).rgb;
        if(srcMotionVector.z < 0.001)
        {
            vec2 uv = (vec2(iPxDilatedMotionVectorPos.xy)+ vec2(0.5, 0.5)) * inv_renderSize;
            vec2 device = uv * vec2(2.0) - vec2(1.0);
            vec4 prev_clip_pos = transform * vec4(device.xy, depthZ, 1.0);
            vec2 prev_screen_pos = ((prev_clip_pos.xy / prev_clip_pos.w) + vec2(1.0))*vec2(0.5);
            srcMotionVector.xy = prev_screen_pos - uv;
        }
        else
        {
            srcMotionVector.xy = (srcMotionVector.xy -vec2(4.999924e-01,4.999924e-01)) / vec2(2.495000e-01,2.495000e-01);
            srcMotionVector.xy = srcMotionVector.xy / vec2(-2.0);
            is_movable_obj = true;
        }
        return srcMotionVector.xy;
    }
    return vec2(0.0, 0.0);
    
}
const ivec2 offset_array[4] = ivec2[4](ivec2(-1, 0), ivec2(1, 0), ivec2(0, 1), ivec2(0, -1));
void computeGameFieldMvs(ivec2 iPxPos) 
{
    float fViewSpaceDepth = LoadInputDepth(iPxPos);
    bool is_movable_obj;
    vec2 fGameMotionVector = LoadInputMotionVector(iPxPos, fViewSpaceDepth, is_movable_obj);
    vec2 uv = vec2(iPxPos) * inv_renderSize; 
    
    uint uHighPriorityFactorPrimary = getPriorityFactorFromViewSpaceDepth(fViewSpaceDepth);
    uint uLowPriorityFactor = 0u;
    highp uint uPriority = PackVectorFieldPriorityFactor(1u, uHighPriorityFactorPrimary, uLowPriorityFactor); 
    
    vec2 fInterpolatedLocationUv =  vec2(iPxPos) * inv_renderSize + fGameMotionVector * 0.5;
    BilinearSamplingData bilinearInfo = GetBilinearSamplingData(fInterpolatedLocationUv, renderSize);
    if (all(lessThan(bilinearInfo.iBasePos, renderSize))  && all(greaterThan(bilinearInfo.iBasePos, ivec2(0,0))))
    {
        highp uint packedVectorPrimary = PackVectorFieldEntries(uPriority, fGameMotionVector * 0.5);
        UpdateGameMotionVectorField(bilinearInfo.iBasePos, packedVectorPrimary);
    }
}

layout(local_size_x = 16, local_size_y = 16) in;
void main() 
{
    ivec2 iPxPos = ivec2(gl_GlobalInvocationID.xy);
    if (all(lessThan(iPxPos.xy, renderSize)))
    {
        computeGameFieldMvs(iPxPos);
    }
    
}
