layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

struct _10
{
    mat4 TranslatedWorldToClip;
    mat4 RelativeWorldToClip;
    mat4 ClipToRelativeWorld;
    mat4 TranslatedWorldToView;
    mat4 ViewToTranslatedWorld;
    mat4 TranslatedWorldToCameraView;
    mat4 CameraViewToTranslatedWorld;
    mat4 ViewToClip;
    mat4 ViewToClipNoAA;
    mat4 ClipToView;
    mat4 ClipToTranslatedWorld;
    mat4 SVPositionToTranslatedWorld;
    mat4 ScreenToRelativeWorld;
    mat4 ScreenToTranslatedWorld;
    mat4 MobileMultiviewShadowTransform;
    vec3 ViewTilePosition;
    vec3 MatrixTilePosition;
    vec3 ViewForward;
    vec3 ViewUp;
    vec3 ViewRight;
    vec3 HMDViewNoRollUp;
    vec3 HMDViewNoRollRight;
    vec4 InvDeviceZToWorldZTransform;
    vec4 ScreenPositionScaleBias;
    vec3 RelativeWorldCameraOrigin;
    vec3 TranslatedWorldCameraOrigin;
    vec3 RelativeWorldViewOrigin;
    vec3 RelativePreViewTranslation;
    mat4 PrevViewToClip;
    mat4 PrevClipToView;
    mat4 PrevTranslatedWorldToClip;
    mat4 PrevTranslatedWorldToView;
    mat4 PrevViewToTranslatedWorld;
    mat4 PrevTranslatedWorldToCameraView;
    mat4 PrevCameraViewToTranslatedWorld;
    vec3 PrevTranslatedWorldCameraOrigin;
    vec3 PrevRelativeWorldCameraOrigin;
    vec3 PrevRelativeWorldViewOrigin;
    vec3 RelativePrevPreViewTranslation;
    mat4 PrevClipToRelativeWorld;
    mat4 PrevScreenToTranslatedWorld;
    mat4 ClipToPrevClip;
    mat4 ClipToPrevClipWithAA;
    vec4 TemporalAAJitter;
    vec4 GlobalClippingPlane;
    vec2 FieldOfViewWideAngles;
    vec2 PrevFieldOfViewWideAngles;
    vec4 ViewRectMin;
    vec4 ViewSizeAndInvSize;
    uvec4 ViewRectMinAndSize;
    vec4 LightProbeSizeRatioAndInvSizeRatio;
    vec4 BufferSizeAndInvSize;
    vec4 BufferBilinearUVMinMax;
    vec4 ScreenToViewSpace;
    vec2 BufferToSceneTextureScale;
    vec2 ResolutionFractionAndInv;
    int NumSceneColorMSAASamples;
    float ProjectionDepthThicknessScale;
    float PreExposure;
    float OneOverPreExposure;
    vec4 DiffuseOverrideParameter;
    vec4 SpecularOverrideParameter;
    vec4 NormalOverrideParameter;
    vec2 RoughnessOverrideParameter;
    float PrevFrameGameTime;
    float PrevFrameRealTime;
    float OutOfBoundsMask;
    vec3 WorldCameraMovementSinceLastFrame;
    float CullingSign;
    float NearPlane;
    float GameTime;
    float RealTime;
    float DeltaTime;
    float MaterialTextureMipBias;
    float MaterialTextureDerivativeMultiply;
    uint Random;
    uint FrameNumber;
    uint FrameCounter;
    uint StateFrameIndexMod8;
    uint StateFrameIndex;
    uint DebugViewModeMask;
    uint WorldIsPaused;
    float CameraCut;
    float UnlitViewmodeMask;
    vec4 DirectionalLightColor;
    vec3 DirectionalLightDirection;
    vec4 TranslucencyLightingVolumeMin[2];
    vec4 TranslucencyLightingVolumeInvSize[2];
    vec4 TemporalAAParams;
    vec4 CircleDOFParams;
    float DepthOfFieldSensorWidth;
    float DepthOfFieldFocalDistance;
    float DepthOfFieldScale;
    float DepthOfFieldFocalLength;
    float DepthOfFieldFocalRegion;
    float DepthOfFieldNearTransitionRegion;
    float DepthOfFieldFarTransitionRegion;
    float MotionBlurNormalizedToPixel;
    float GeneralPurposeTweak;
    float GeneralPurposeTweak2;
    float DemosaicVposOffset;
    float DecalDepthBias;
    vec3 IndirectLightingColorScale;
    vec3 PrecomputedIndirectLightingColorScale;
    vec3 PrecomputedIndirectSpecularColorScale;
    vec4 AtmosphereLightDirection[2];
    vec4 AtmosphereLightIlluminanceOnGroundPostTransmittance[2];
    vec4 AtmosphereLightIlluminanceOuterSpace[2];
    vec4 AtmosphereLightDiscLuminance[2];
    vec4 AtmosphereLightDiscCosHalfApexAngle_PPTrans[2];
    vec4 SkyViewLutSizeAndInvSize;
    vec3 SkyCameraTranslatedWorldOrigin;
    vec4 SkyPlanetTranslatedWorldCenterAndViewHeight;
    mat4 SkyViewLutReferential;
    vec4 SkyAtmosphereSkyLuminanceFactor;
    float SkyAtmospherePresentInScene;
    float SkyAtmosphereHeightFogContribution;
    float SkyAtmosphereBottomRadiusKm;
    float SkyAtmosphereTopRadiusKm;
    vec4 SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize;
    float SkyAtmosphereAerialPerspectiveStartDepthKm;
    float SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution;
    float SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv;
    float SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm;
    float SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv;
    float SkyAtmosphereApplyCameraAerialPerspectiveVolume;
    vec3 NormalCurvatureToRoughnessScaleBias;
    float RenderingReflectionCaptureMask;
    float RealTimeReflectionCapture;
    float RealTimeReflectionCapturePreExposure;
    vec4 AmbientCubemapTint;
    float AmbientCubemapIntensity;
    float SkyLightApplyPrecomputedBentNormalShadowingFlag;
    float SkyLightAffectReflectionFlag;
    float SkyLightAffectGlobalIlluminationFlag;
    vec4 SkyLightColor;
    vec4 MobileSkyIrradianceEnvironmentMap[8];
    float MobilePreviewMode;
    float HMDEyePaddingOffset;
    float ReflectionCubemapMaxMip;
    float ShowDecalsMask;
    uint DistanceFieldAOSpecularOcclusionMode;
    float IndirectCapsuleSelfShadowingIntensity;
    vec3 ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight;
    int StereoPassIndex;
    vec4 GlobalVolumeTranslatedCenterAndExtent[6];
    vec4 GlobalVolumeTranslatedWorldToUVAddAndMul[6];
    vec4 GlobalDistanceFieldMipTranslatedWorldToUVScale[6];
    vec4 GlobalDistanceFieldMipTranslatedWorldToUVBias[6];
    float GlobalDistanceFieldMipFactor;
    float GlobalDistanceFieldMipTransition;
    int GlobalDistanceFieldClipmapSizeInPages;
    vec3 GlobalDistanceFieldInvPageAtlasSize;
    vec3 GlobalDistanceFieldInvCoverageAtlasSize;
    float GlobalVolumeDimension;
    float GlobalVolumeTexelSize;
    float MaxGlobalDFAOConeDistance;
    uint NumGlobalSDFClipmaps;
    float CoveredExpandSurfaceScale;
    float NotCoveredExpandSurfaceScale;
    float NotCoveredMinStepScale;
    float DitheredTransparencyStepThreshold;
    float DitheredTransparencyTraceThreshold;
    ivec2 CursorPosition;
    float bCheckerboardSubsurfaceProfileRendering;
    vec3 VolumetricFogInvGridSize;
    vec3 VolumetricFogGridZParams;
    vec2 VolumetricFogSVPosToVolumeUV;
    vec2 VolumetricFogViewGridUVToPrevViewRectUV;
    vec2 VolumetricFogPrevViewGridRectUVToResourceUV;
    vec2 VolumetricFogPrevUVMax;
    vec2 VolumetricFogScreenToResourceUV;
    vec2 VolumetricFogUVMax;
    float VolumetricFogMaxDistance;
    vec3 VolumetricLightmapWorldToUVScale;
    vec3 VolumetricLightmapWorldToUVAdd;
    vec3 VolumetricLightmapIndirectionTextureSize;
    float VolumetricLightmapBrickSize;
    vec3 VolumetricLightmapBrickTexelSize;
    float IndirectLightingCacheShowFlag;
    float EyeToPixelSpreadAngle;
    vec4 XRPassthroughCameraUVs[2];
    float GlobalVirtualTextureMipBias;
    uint VirtualTextureFeedbackShift;
    uint VirtualTextureFeedbackMask;
    uint VirtualTextureFeedbackStride;
    uint VirtualTextureFeedbackJitterOffset;
    uint VirtualTextureFeedbackSampleOffset;
    vec4 RuntimeVirtualTextureMipLevel;
    vec2 RuntimeVirtualTexturePackHeight;
    vec4 RuntimeVirtualTextureDebugParams;
    float OverrideLandscapeLOD;
    int FarShadowStaticMeshLODBias;
    float MinRoughness;
    vec4 HairRenderInfo;
    uint EnableSkyLight;
    uint HairRenderInfoBits;
    uint HairComponents;
    float bSubsurfacePostprocessEnabled;
    vec4 SSProfilesTextureSizeAndInvSize;
    vec4 SSProfilesPreIntegratedTextureSizeAndInvSize;
    vec4 SpecularProfileTextureSizeAndInvSize;
    vec3 PhysicsFieldClipmapCenter;
    float PhysicsFieldClipmapDistance;
    int PhysicsFieldClipmapResolution;
    int PhysicsFieldClipmapExponent;
    int PhysicsFieldClipmapCount;
    int PhysicsFieldTargetCount;
    ivec4 PhysicsFieldTargets[32];
    uint GPUSceneViewId;
    float ViewResolutionFraction;
    float SubSurfaceColorAsTransmittanceAtDistanceInMeters;
    vec4 TanAndInvTanHalfFOV;
    vec4 PrevTanAndInvTanHalfFOV;
    vec4 GlintLUTParameters0;
    vec4 GlintLUTParameters1;
    uint bShadingEnergyConservation;
    uint bShadingEnergyPreservation;
    vec4 RectLightAtlasSizeAndInvSize;
    float RectLightAtlasMaxMipLevel;
    vec4 IESAtlasSizeAndInvSize;
    vec3 TLASRelativePreViewTranslation;
    vec3 TLASViewTilePosition;
};

layout(binding = 0, std140) uniform type_RootShaderParameters
{
    float FurthestReflectionCaptureDistance;
    float ReactiveMaskReflectionScale;
    float ReactiveMaskRoughnessScale;
    float ReactiveMaskRoughnessBias;
    float ReactiveMaskReflectionLumaBias;
    float ReactiveHistoryTranslucencyBias;
    float ReactiveHistoryTranslucencyLumaBias;
    float ReactiveMaskTranslucencyBias;
    float ReactiveMaskTranslucencyLumaBias;
    float ReactiveMaskPreDOFTranslucencyScale;
    uint ReactiveMaskPreDOFTranslucencyMax;
    float ReactiveMaskTranslucencyMaxDistance;
    float ForceLitReactiveValue;
    float CustomStencilReactiveMaskScale;
    float CustomStencilReactiveHistoryScale;
    float DeferredDecalReactiveMaskScale;
    float DeferredDecalReactiveHistoryScale;
    float ReactiveMaskTAAResponsiveValue;
    float ReactiveHistoryTAAResponsiveValue;
    uint ReactiveShadingModelID;
    uint LumenSpecularCurrentFrame;
    uint CustomStencilMask;
    uint CustomStencilShift;
} _RootShaderParameters;

layout(binding = 1, std140) uniform type_UniformBufferConstants_View
{
    mat4 View_TranslatedWorldToClip;
    mat4 View_RelativeWorldToClip;
    mat4 View_ClipToRelativeWorld;
    mat4 View_TranslatedWorldToView;
    mat4 View_ViewToTranslatedWorld;
    mat4 View_TranslatedWorldToCameraView;
    mat4 View_CameraViewToTranslatedWorld;
    mat4 View_ViewToClip;
    mat4 View_ViewToClipNoAA;
    mat4 View_ClipToView;
    mat4 View_ClipToTranslatedWorld;
    mat4 View_SVPositionToTranslatedWorld;
    mat4 View_ScreenToRelativeWorld;
    mat4 View_ScreenToTranslatedWorld;
    mat4 View_MobileMultiviewShadowTransform;
    vec3 View_ViewTilePosition;
    float PrePadding_View_972;
    vec3 View_MatrixTilePosition;
    float PrePadding_View_988;
    vec3 View_ViewForward;
    float PrePadding_View_1004;
    vec3 View_ViewUp;
    float PrePadding_View_1020;
    vec3 View_ViewRight;
    float PrePadding_View_1036;
    vec3 View_HMDViewNoRollUp;
    float PrePadding_View_1052;
    vec3 View_HMDViewNoRollRight;
    float PrePadding_View_1068;
    vec4 View_InvDeviceZToWorldZTransform;
    vec4 View_ScreenPositionScaleBias;
    vec3 View_RelativeWorldCameraOrigin;
    float PrePadding_View_1116;
    vec3 View_TranslatedWorldCameraOrigin;
    float PrePadding_View_1132;
    vec3 View_RelativeWorldViewOrigin;
    float PrePadding_View_1148;
    vec3 View_RelativePreViewTranslation;
    float PrePadding_View_1164;
    mat4 View_PrevViewToClip;
    mat4 View_PrevClipToView;
    mat4 View_PrevTranslatedWorldToClip;
    mat4 View_PrevTranslatedWorldToView;
    mat4 View_PrevViewToTranslatedWorld;
    mat4 View_PrevTranslatedWorldToCameraView;
    mat4 View_PrevCameraViewToTranslatedWorld;
    vec3 View_PrevTranslatedWorldCameraOrigin;
    float PrePadding_View_1628;
    vec3 View_PrevRelativeWorldCameraOrigin;
    float PrePadding_View_1644;
    vec3 View_PrevRelativeWorldViewOrigin;
    float PrePadding_View_1660;
    vec3 View_RelativePrevPreViewTranslation;
    float PrePadding_View_1676;
    mat4 View_PrevClipToRelativeWorld;
    mat4 View_PrevScreenToTranslatedWorld;
    mat4 View_ClipToPrevClip;
    mat4 View_ClipToPrevClipWithAA;
    vec4 View_TemporalAAJitter;
    vec4 View_GlobalClippingPlane;
    vec2 View_FieldOfViewWideAngles;
    vec2 View_PrevFieldOfViewWideAngles;
    vec4 View_ViewRectMin;
    vec4 View_ViewSizeAndInvSize;
    uvec4 View_ViewRectMinAndSize;
    vec4 View_LightProbeSizeRatioAndInvSizeRatio;
    vec4 View_BufferSizeAndInvSize;
    vec4 View_BufferBilinearUVMinMax;
    vec4 View_ScreenToViewSpace;
    vec2 View_BufferToSceneTextureScale;
    vec2 View_ResolutionFractionAndInv;
    int View_NumSceneColorMSAASamples;
    float View_ProjectionDepthThicknessScale;
    float View_PreExposure;
    float View_OneOverPreExposure;
    vec4 View_DiffuseOverrideParameter;
    vec4 View_SpecularOverrideParameter;
    vec4 View_NormalOverrideParameter;
    vec2 View_RoughnessOverrideParameter;
    float View_PrevFrameGameTime;
    float View_PrevFrameRealTime;
    float View_OutOfBoundsMask;
    float PrePadding_View_2196;
    float PrePadding_View_2200;
    float PrePadding_View_2204;
    vec3 View_WorldCameraMovementSinceLastFrame;
    float View_CullingSign;
    float View_NearPlane;
    float View_GameTime;
    float View_RealTime;
    float View_DeltaTime;
    float View_MaterialTextureMipBias;
    float View_MaterialTextureDerivativeMultiply;
    uint View_Random;
    uint View_FrameNumber;
    uint View_FrameCounter;
    uint View_StateFrameIndexMod8;
    uint View_StateFrameIndex;
    uint View_DebugViewModeMask;
    uint View_WorldIsPaused;
    float View_CameraCut;
    float View_UnlitViewmodeMask;
    float PrePadding_View_2284;
    vec4 View_DirectionalLightColor;
    vec3 View_DirectionalLightDirection;
    float PrePadding_View_2316;
    vec4 View_TranslucencyLightingVolumeMin[2];
    vec4 View_TranslucencyLightingVolumeInvSize[2];
    vec4 View_TemporalAAParams;
    vec4 View_CircleDOFParams;
    float View_DepthOfFieldSensorWidth;
    float View_DepthOfFieldFocalDistance;
    float View_DepthOfFieldScale;
    float View_DepthOfFieldFocalLength;
    float View_DepthOfFieldFocalRegion;
    float View_DepthOfFieldNearTransitionRegion;
    float View_DepthOfFieldFarTransitionRegion;
    float View_MotionBlurNormalizedToPixel;
    float View_GeneralPurposeTweak;
    float View_GeneralPurposeTweak2;
    float View_DemosaicVposOffset;
    float View_DecalDepthBias;
    vec3 View_IndirectLightingColorScale;
    float PrePadding_View_2476;
    vec3 View_PrecomputedIndirectLightingColorScale;
    float PrePadding_View_2492;
    vec3 View_PrecomputedIndirectSpecularColorScale;
    float PrePadding_View_2508;
    vec4 View_AtmosphereLightDirection[2];
    vec4 View_AtmosphereLightIlluminanceOnGroundPostTransmittance[2];
    vec4 View_AtmosphereLightIlluminanceOuterSpace[2];
    vec4 View_AtmosphereLightDiscLuminance[2];
    vec4 View_AtmosphereLightDiscCosHalfApexAngle_PPTrans[2];
    vec4 View_SkyViewLutSizeAndInvSize;
    vec3 View_SkyCameraTranslatedWorldOrigin;
    float PrePadding_View_2700;
    vec4 View_SkyPlanetTranslatedWorldCenterAndViewHeight;
    mat4 View_SkyViewLutReferential;
    vec4 View_SkyAtmosphereSkyLuminanceFactor;
    float View_SkyAtmospherePresentInScene;
    float View_SkyAtmosphereHeightFogContribution;
    float View_SkyAtmosphereBottomRadiusKm;
    float View_SkyAtmosphereTopRadiusKm;
    vec4 View_SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize;
    float View_SkyAtmosphereAerialPerspectiveStartDepthKm;
    float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution;
    float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv;
    float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm;
    float View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv;
    float View_SkyAtmosphereApplyCameraAerialPerspectiveVolume;
    float PrePadding_View_2856;
    float PrePadding_View_2860;
    vec3 View_NormalCurvatureToRoughnessScaleBias;
    float View_RenderingReflectionCaptureMask;
    float View_RealTimeReflectionCapture;
    float View_RealTimeReflectionCapturePreExposure;
    float PrePadding_View_2888;
    float PrePadding_View_2892;
    vec4 View_AmbientCubemapTint;
    float View_AmbientCubemapIntensity;
    float View_SkyLightApplyPrecomputedBentNormalShadowingFlag;
    float View_SkyLightAffectReflectionFlag;
    float View_SkyLightAffectGlobalIlluminationFlag;
    vec4 View_SkyLightColor;
    vec4 View_MobileSkyIrradianceEnvironmentMap[8];
    float View_MobilePreviewMode;
    float View_HMDEyePaddingOffset;
    float View_ReflectionCubemapMaxMip;
    float View_ShowDecalsMask;
    uint View_DistanceFieldAOSpecularOcclusionMode;
    float View_IndirectCapsuleSelfShadowingIntensity;
    float PrePadding_View_3096;
    float PrePadding_View_3100;
    vec3 View_ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight;
    int View_StereoPassIndex;
    vec4 View_GlobalVolumeTranslatedCenterAndExtent[6];
    vec4 View_GlobalVolumeTranslatedWorldToUVAddAndMul[6];
    vec4 View_GlobalDistanceFieldMipTranslatedWorldToUVScale[6];
    vec4 View_GlobalDistanceFieldMipTranslatedWorldToUVBias[6];
    float View_GlobalDistanceFieldMipFactor;
    float View_GlobalDistanceFieldMipTransition;
    int View_GlobalDistanceFieldClipmapSizeInPages;
    int PrePadding_View_3516;
    vec3 View_GlobalDistanceFieldInvPageAtlasSize;
    float PrePadding_View_3532;
    vec3 View_GlobalDistanceFieldInvCoverageAtlasSize;
    float View_GlobalVolumeDimension;
    float View_GlobalVolumeTexelSize;
    float View_MaxGlobalDFAOConeDistance;
    uint View_NumGlobalSDFClipmaps;
    float View_CoveredExpandSurfaceScale;
    float View_NotCoveredExpandSurfaceScale;
    float View_NotCoveredMinStepScale;
    float View_DitheredTransparencyStepThreshold;
    float View_DitheredTransparencyTraceThreshold;
    ivec2 View_CursorPosition;
    float View_bCheckerboardSubsurfaceProfileRendering;
    float PrePadding_View_3596;
    vec3 View_VolumetricFogInvGridSize;
    float PrePadding_View_3612;
    vec3 View_VolumetricFogGridZParams;
    float PrePadding_View_3628;
    vec2 View_VolumetricFogSVPosToVolumeUV;
    vec2 View_VolumetricFogViewGridUVToPrevViewRectUV;
    vec2 View_VolumetricFogPrevViewGridRectUVToResourceUV;
    vec2 View_VolumetricFogPrevUVMax;
    vec2 View_VolumetricFogScreenToResourceUV;
    vec2 View_VolumetricFogUVMax;
    float View_VolumetricFogMaxDistance;
    float PrePadding_View_3684;
    float PrePadding_View_3688;
    float PrePadding_View_3692;
    vec3 View_VolumetricLightmapWorldToUVScale;
    float PrePadding_View_3708;
    vec3 View_VolumetricLightmapWorldToUVAdd;
    float PrePadding_View_3724;
    vec3 View_VolumetricLightmapIndirectionTextureSize;
    float View_VolumetricLightmapBrickSize;
    vec3 View_VolumetricLightmapBrickTexelSize;
    float View_IndirectLightingCacheShowFlag;
    float View_EyeToPixelSpreadAngle;
    float PrePadding_View_3764;
    float PrePadding_View_3768;
    float PrePadding_View_3772;
    vec4 View_XRPassthroughCameraUVs[2];
    float View_GlobalVirtualTextureMipBias;
    uint View_VirtualTextureFeedbackShift;
    uint View_VirtualTextureFeedbackMask;
    uint View_VirtualTextureFeedbackStride;
    uint View_VirtualTextureFeedbackJitterOffset;
    uint View_VirtualTextureFeedbackSampleOffset;
    uint PrePadding_View_3832;
    uint PrePadding_View_3836;
    vec4 View_RuntimeVirtualTextureMipLevel;
    vec2 View_RuntimeVirtualTexturePackHeight;
    float PrePadding_View_3864;
    float PrePadding_View_3868;
    vec4 View_RuntimeVirtualTextureDebugParams;
    float View_OverrideLandscapeLOD;
    int View_FarShadowStaticMeshLODBias;
    float View_MinRoughness;
    float PrePadding_View_3900;
    vec4 View_HairRenderInfo;
    uint View_EnableSkyLight;
    uint View_HairRenderInfoBits;
    uint View_HairComponents;
    float View_bSubsurfacePostprocessEnabled;
    vec4 View_SSProfilesTextureSizeAndInvSize;
    vec4 View_SSProfilesPreIntegratedTextureSizeAndInvSize;
    vec4 View_SpecularProfileTextureSizeAndInvSize;
    vec3 View_PhysicsFieldClipmapCenter;
    float View_PhysicsFieldClipmapDistance;
    int View_PhysicsFieldClipmapResolution;
    int View_PhysicsFieldClipmapExponent;
    int View_PhysicsFieldClipmapCount;
    int View_PhysicsFieldTargetCount;
    ivec4 View_PhysicsFieldTargets[32];
    uint View_GPUSceneViewId;
    float View_ViewResolutionFraction;
    float View_SubSurfaceColorAsTransmittanceAtDistanceInMeters;
    float PrePadding_View_4540;
    vec4 View_TanAndInvTanHalfFOV;
    vec4 View_PrevTanAndInvTanHalfFOV;
    vec4 View_GlintLUTParameters0;
    vec4 View_GlintLUTParameters1;
    uint BindlessSampler_View_MaterialTextureBilinearWrapedSampler;
    uint PrePadding_View_4612;
    uint BindlessSampler_View_MaterialTextureBilinearClampedSampler;
    uint PrePadding_View_4620;
    uint BindlessResource_View_VolumetricLightmapIndirectionTexture;
    uint PrePadding_View_4628;
    uint BindlessResource_View_VolumetricLightmapBrickAmbientVector;
    uint PrePadding_View_4636;
    uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients0;
    uint PrePadding_View_4644;
    uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients1;
    uint PrePadding_View_4652;
    uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients2;
    uint PrePadding_View_4660;
    uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients3;
    uint PrePadding_View_4668;
    uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients4;
    uint PrePadding_View_4676;
    uint BindlessResource_View_VolumetricLightmapBrickSHCoefficients5;
    uint PrePadding_View_4684;
    uint BindlessResource_View_SkyBentNormalBrickTexture;
    uint PrePadding_View_4692;
    uint BindlessResource_View_DirectionalLightShadowingBrickTexture;
    uint PrePadding_View_4700;
    uint BindlessSampler_View_VolumetricLightmapBrickAmbientVectorSampler;
    uint PrePadding_View_4708;
    uint BindlessSampler_View_VolumetricLightmapTextureSampler0;
    uint PrePadding_View_4716;
    uint BindlessSampler_View_VolumetricLightmapTextureSampler1;
    uint PrePadding_View_4724;
    uint BindlessSampler_View_VolumetricLightmapTextureSampler2;
    uint PrePadding_View_4732;
    uint BindlessSampler_View_VolumetricLightmapTextureSampler3;
    uint PrePadding_View_4740;
    uint BindlessSampler_View_VolumetricLightmapTextureSampler4;
    uint PrePadding_View_4748;
    uint BindlessSampler_View_VolumetricLightmapTextureSampler5;
    uint PrePadding_View_4756;
    uint BindlessSampler_View_SkyBentNormalTextureSampler;
    uint PrePadding_View_4764;
    uint BindlessSampler_View_DirectionalLightShadowingTextureSampler;
    uint PrePadding_View_4772;
    uint BindlessResource_View_GlobalDistanceFieldPageAtlasTexture;
    uint PrePadding_View_4780;
    uint BindlessResource_View_GlobalDistanceFieldCoverageAtlasTexture;
    uint PrePadding_View_4788;
    uint BindlessResource_View_GlobalDistanceFieldPageTableTexture;
    uint PrePadding_View_4796;
    uint BindlessResource_View_GlobalDistanceFieldMipTexture;
    uint PrePadding_View_4804;
    uint BindlessSampler_View_GlobalDistanceFieldPageAtlasTextureSampler;
    uint PrePadding_View_4812;
    uint BindlessSampler_View_GlobalDistanceFieldCoverageAtlasTextureSampler;
    uint PrePadding_View_4820;
    uint BindlessSampler_View_GlobalDistanceFieldMipTextureSampler;
    uint PrePadding_View_4828;
    uint BindlessResource_View_AtmosphereTransmittanceTexture;
    uint PrePadding_View_4836;
    uint BindlessSampler_View_AtmosphereTransmittanceTextureSampler;
    uint PrePadding_View_4844;
    uint BindlessResource_View_AtmosphereIrradianceTexture;
    uint PrePadding_View_4852;
    uint BindlessSampler_View_AtmosphereIrradianceTextureSampler;
    uint PrePadding_View_4860;
    uint BindlessResource_View_AtmosphereInscatterTexture;
    uint PrePadding_View_4868;
    uint BindlessSampler_View_AtmosphereInscatterTextureSampler;
    uint PrePadding_View_4876;
    uint BindlessResource_View_PerlinNoiseGradientTexture;
    uint PrePadding_View_4884;
    uint BindlessSampler_View_PerlinNoiseGradientTextureSampler;
    uint PrePadding_View_4892;
    uint BindlessResource_View_PerlinNoise3DTexture;
    uint PrePadding_View_4900;
    uint BindlessSampler_View_PerlinNoise3DTextureSampler;
    uint PrePadding_View_4908;
    uint BindlessResource_View_SobolSamplingTexture;
    uint PrePadding_View_4916;
    uint BindlessSampler_View_SharedPointWrappedSampler;
    uint PrePadding_View_4924;
    uint BindlessSampler_View_SharedPointClampedSampler;
    uint PrePadding_View_4932;
    uint BindlessSampler_View_SharedBilinearWrappedSampler;
    uint PrePadding_View_4940;
    uint BindlessSampler_View_SharedBilinearClampedSampler;
    uint PrePadding_View_4948;
    uint BindlessSampler_View_SharedBilinearAnisoClampedSampler;
    uint PrePadding_View_4956;
    uint BindlessSampler_View_SharedTrilinearWrappedSampler;
    uint PrePadding_View_4964;
    uint BindlessSampler_View_SharedTrilinearClampedSampler;
    uint PrePadding_View_4972;
    uint BindlessResource_View_PreIntegratedBRDF;
    uint PrePadding_View_4980;
    uint BindlessSampler_View_PreIntegratedBRDFSampler;
    uint PrePadding_View_4988;
    uint BindlessResource_View_SkyIrradianceEnvironmentMap;
    uint PrePadding_View_4996;
    uint BindlessResource_View_TransmittanceLutTexture;
    uint PrePadding_View_5004;
    uint BindlessSampler_View_TransmittanceLutTextureSampler;
    uint PrePadding_View_5012;
    uint BindlessResource_View_SkyViewLutTexture;
    uint PrePadding_View_5020;
    uint BindlessSampler_View_SkyViewLutTextureSampler;
    uint PrePadding_View_5028;
    uint BindlessResource_View_DistantSkyLightLutTexture;
    uint PrePadding_View_5036;
    uint BindlessSampler_View_DistantSkyLightLutTextureSampler;
    uint PrePadding_View_5044;
    uint BindlessResource_View_CameraAerialPerspectiveVolume;
    uint PrePadding_View_5052;
    uint BindlessSampler_View_CameraAerialPerspectiveVolumeSampler;
    uint PrePadding_View_5060;
    uint BindlessResource_View_CameraAerialPerspectiveVolumeMieOnly;
    uint PrePadding_View_5068;
    uint BindlessSampler_View_CameraAerialPerspectiveVolumeMieOnlySampler;
    uint PrePadding_View_5076;
    uint BindlessResource_View_CameraAerialPerspectiveVolumeRayOnly;
    uint PrePadding_View_5084;
    uint BindlessSampler_View_CameraAerialPerspectiveVolumeRayOnlySampler;
    uint PrePadding_View_5092;
    uint BindlessResource_View_HairScatteringLUTTexture;
    uint PrePadding_View_5100;
    uint BindlessSampler_View_HairScatteringLUTSampler;
    uint PrePadding_View_5108;
    uint BindlessResource_View_GGXLTCMatTexture;
    uint PrePadding_View_5116;
    uint BindlessSampler_View_GGXLTCMatSampler;
    uint PrePadding_View_5124;
    uint BindlessResource_View_GGXLTCAmpTexture;
    uint PrePadding_View_5132;
    uint BindlessSampler_View_GGXLTCAmpSampler;
    uint PrePadding_View_5140;
    uint BindlessResource_View_SheenLTCTexture;
    uint PrePadding_View_5148;
    uint BindlessSampler_View_SheenLTCSampler;
    uint PrePadding_View_5156;
    uint View_bShadingEnergyConservation;
    uint View_bShadingEnergyPreservation;
    uint BindlessResource_View_ShadingEnergyGGXSpecTexture;
    uint PrePadding_View_5172;
    uint BindlessResource_View_ShadingEnergyGGXGlassTexture;
    uint PrePadding_View_5180;
    uint BindlessResource_View_ShadingEnergyClothSpecTexture;
    uint PrePadding_View_5188;
    uint BindlessResource_View_ShadingEnergyDiffuseTexture;
    uint PrePadding_View_5196;
    uint BindlessSampler_View_ShadingEnergySampler;
    uint PrePadding_View_5204;
    uint BindlessResource_View_GlintTexture;
    uint PrePadding_View_5212;
    uint BindlessSampler_View_GlintSampler;
    uint PrePadding_View_5220;
    uint BindlessResource_View_SimpleVolumeTexture;
    uint PrePadding_View_5228;
    uint BindlessSampler_View_SimpleVolumeTextureSampler;
    uint PrePadding_View_5236;
    uint BindlessResource_View_SimpleVolumeEnvTexture;
    uint PrePadding_View_5244;
    uint BindlessSampler_View_SimpleVolumeEnvTextureSampler;
    uint PrePadding_View_5252;
    uint BindlessResource_View_SSProfilesTexture;
    uint PrePadding_View_5260;
    uint BindlessSampler_View_SSProfilesSampler;
    uint PrePadding_View_5268;
    uint BindlessSampler_View_SSProfilesTransmissionSampler;
    uint PrePadding_View_5276;
    uint BindlessResource_View_SSProfilesPreIntegratedTexture;
    uint PrePadding_View_5284;
    uint BindlessSampler_View_SSProfilesPreIntegratedSampler;
    uint PrePadding_View_5292;
    uint BindlessResource_View_SpecularProfileTexture;
    uint PrePadding_View_5300;
    uint BindlessSampler_View_SpecularProfileSampler;
    uint PrePadding_View_5308;
    uint BindlessResource_View_WaterIndirection;
    uint PrePadding_View_5316;
    uint BindlessResource_View_WaterData;
    uint PrePadding_View_5324;
    vec4 View_RectLightAtlasSizeAndInvSize;
    float View_RectLightAtlasMaxMipLevel;
    float PrePadding_View_5348;
    uint BindlessResource_View_RectLightAtlasTexture;
    uint PrePadding_View_5356;
    uint BindlessSampler_View_RectLightAtlasSampler;
    uint PrePadding_View_5364;
    uint PrePadding_View_5368;
    uint PrePadding_View_5372;
    vec4 View_IESAtlasSizeAndInvSize;
    uint BindlessResource_View_IESAtlasTexture;
    uint PrePadding_View_5396;
    uint BindlessSampler_View_IESAtlasSampler;
    uint PrePadding_View_5404;
    uint BindlessSampler_View_LandscapeWeightmapSampler;
    uint PrePadding_View_5412;
    uint BindlessResource_View_LandscapeIndirection;
    uint PrePadding_View_5420;
    uint BindlessResource_View_LandscapePerComponentData;
    uint PrePadding_View_5428;
    uint BindlessResource_View_VTFeedbackBuffer;
    uint PrePadding_View_5436;
    uint BindlessResource_View_PhysicsFieldClipmapBuffer;
    uint PrePadding_View_5444;
    uint PrePadding_View_5448;
    uint PrePadding_View_5452;
    vec3 View_TLASRelativePreViewTranslation;
    float PrePadding_View_5468;
    vec3 View_TLASViewTilePosition;
} UniformBufferConstants_View;

layout(binding = 14, r32f) uniform writeonly highp image2D ReactiveMask;
layout(binding = 15, r32f) uniform writeonly highp image2D CompositeMask;
uniform highp sampler2D SPIRV_Cross_CombinedGBufferBSPIRV_Cross_DummySampler;
uniform highp sampler2D SPIRV_Cross_CombinedGBufferDSPIRV_Cross_DummySampler;
uniform highp sampler2D SPIRV_Cross_CombinedSceneColorSPIRV_Cross_DummySampler;
uniform highp sampler2D SPIRV_Cross_CombinedSceneColorPreAlphaSPIRV_Cross_DummySampler;
uniform highp sampler2D SPIRV_Cross_CombinedInputDepthSPIRV_Cross_DummySampler;
uniform highp usampler2D SPIRV_Cross_CombinedCustomStencilSPIRV_Cross_DummySampler;
uniform highp usampler2D SPIRV_Cross_CombinedStencilTextureSPIRV_Cross_DummySampler;
uniform highp sampler2D SPIRV_Cross_CombinedReflectionTextureSampler;
uniform highp sampler2D SPIRV_Cross_CombinedInputSeparateTranslucencySampler;
uniform highp sampler2D SPIRV_Cross_CombinedDBufferASampler;
uniform highp sampler2D SPIRV_Cross_CombinedInputVelocitySPIRV_Cross_DummySampler;
uniform highp sampler2D SPIRV_Cross_CombinedLumenSpecularSampler;

vec2 _338;

void main()
{
    _10 View = _10(UniformBufferConstants_View.View_TranslatedWorldToClip, UniformBufferConstants_View.View_RelativeWorldToClip, UniformBufferConstants_View.View_ClipToRelativeWorld, UniformBufferConstants_View.View_TranslatedWorldToView, UniformBufferConstants_View.View_ViewToTranslatedWorld, UniformBufferConstants_View.View_TranslatedWorldToCameraView, UniformBufferConstants_View.View_CameraViewToTranslatedWorld, UniformBufferConstants_View.View_ViewToClip, UniformBufferConstants_View.View_ViewToClipNoAA, UniformBufferConstants_View.View_ClipToView, UniformBufferConstants_View.View_ClipToTranslatedWorld, UniformBufferConstants_View.View_SVPositionToTranslatedWorld, UniformBufferConstants_View.View_ScreenToRelativeWorld, UniformBufferConstants_View.View_ScreenToTranslatedWorld, UniformBufferConstants_View.View_MobileMultiviewShadowTransform, UniformBufferConstants_View.View_ViewTilePosition, UniformBufferConstants_View.View_MatrixTilePosition, UniformBufferConstants_View.View_ViewForward, UniformBufferConstants_View.View_ViewUp, UniformBufferConstants_View.View_ViewRight, UniformBufferConstants_View.View_HMDViewNoRollUp, UniformBufferConstants_View.View_HMDViewNoRollRight, UniformBufferConstants_View.View_InvDeviceZToWorldZTransform, UniformBufferConstants_View.View_ScreenPositionScaleBias, UniformBufferConstants_View.View_RelativeWorldCameraOrigin, UniformBufferConstants_View.View_TranslatedWorldCameraOrigin, UniformBufferConstants_View.View_RelativeWorldViewOrigin, UniformBufferConstants_View.View_RelativePreViewTranslation, UniformBufferConstants_View.View_PrevViewToClip, UniformBufferConstants_View.View_PrevClipToView, UniformBufferConstants_View.View_PrevTranslatedWorldToClip, UniformBufferConstants_View.View_PrevTranslatedWorldToView, UniformBufferConstants_View.View_PrevViewToTranslatedWorld, UniformBufferConstants_View.View_PrevTranslatedWorldToCameraView, UniformBufferConstants_View.View_PrevCameraViewToTranslatedWorld, UniformBufferConstants_View.View_PrevTranslatedWorldCameraOrigin, UniformBufferConstants_View.View_PrevRelativeWorldCameraOrigin, UniformBufferConstants_View.View_PrevRelativeWorldViewOrigin, UniformBufferConstants_View.View_RelativePrevPreViewTranslation, UniformBufferConstants_View.View_PrevClipToRelativeWorld, UniformBufferConstants_View.View_PrevScreenToTranslatedWorld, UniformBufferConstants_View.View_ClipToPrevClip, UniformBufferConstants_View.View_ClipToPrevClipWithAA, UniformBufferConstants_View.View_TemporalAAJitter, UniformBufferConstants_View.View_GlobalClippingPlane, UniformBufferConstants_View.View_FieldOfViewWideAngles, UniformBufferConstants_View.View_PrevFieldOfViewWideAngles, UniformBufferConstants_View.View_ViewRectMin, UniformBufferConstants_View.View_ViewSizeAndInvSize, UniformBufferConstants_View.View_ViewRectMinAndSize, UniformBufferConstants_View.View_LightProbeSizeRatioAndInvSizeRatio, UniformBufferConstants_View.View_BufferSizeAndInvSize, UniformBufferConstants_View.View_BufferBilinearUVMinMax, UniformBufferConstants_View.View_ScreenToViewSpace, UniformBufferConstants_View.View_BufferToSceneTextureScale, UniformBufferConstants_View.View_ResolutionFractionAndInv, UniformBufferConstants_View.View_NumSceneColorMSAASamples, UniformBufferConstants_View.View_ProjectionDepthThicknessScale, UniformBufferConstants_View.View_PreExposure, UniformBufferConstants_View.View_OneOverPreExposure, UniformBufferConstants_View.View_DiffuseOverrideParameter, UniformBufferConstants_View.View_SpecularOverrideParameter, UniformBufferConstants_View.View_NormalOverrideParameter, UniformBufferConstants_View.View_RoughnessOverrideParameter, UniformBufferConstants_View.View_PrevFrameGameTime, UniformBufferConstants_View.View_PrevFrameRealTime, UniformBufferConstants_View.View_OutOfBoundsMask, UniformBufferConstants_View.View_WorldCameraMovementSinceLastFrame, UniformBufferConstants_View.View_CullingSign, UniformBufferConstants_View.View_NearPlane, UniformBufferConstants_View.View_GameTime, UniformBufferConstants_View.View_RealTime, UniformBufferConstants_View.View_DeltaTime, UniformBufferConstants_View.View_MaterialTextureMipBias, UniformBufferConstants_View.View_MaterialTextureDerivativeMultiply, UniformBufferConstants_View.View_Random, UniformBufferConstants_View.View_FrameNumber, UniformBufferConstants_View.View_FrameCounter, UniformBufferConstants_View.View_StateFrameIndexMod8, UniformBufferConstants_View.View_StateFrameIndex, UniformBufferConstants_View.View_DebugViewModeMask, UniformBufferConstants_View.View_WorldIsPaused, UniformBufferConstants_View.View_CameraCut, UniformBufferConstants_View.View_UnlitViewmodeMask, UniformBufferConstants_View.View_DirectionalLightColor, UniformBufferConstants_View.View_DirectionalLightDirection, vec4[](UniformBufferConstants_View.View_TranslucencyLightingVolumeMin[0], UniformBufferConstants_View.View_TranslucencyLightingVolumeMin[1]), vec4[](UniformBufferConstants_View.View_TranslucencyLightingVolumeInvSize[0], UniformBufferConstants_View.View_TranslucencyLightingVolumeInvSize[1]), UniformBufferConstants_View.View_TemporalAAParams, UniformBufferConstants_View.View_CircleDOFParams, UniformBufferConstants_View.View_DepthOfFieldSensorWidth, UniformBufferConstants_View.View_DepthOfFieldFocalDistance, UniformBufferConstants_View.View_DepthOfFieldScale, UniformBufferConstants_View.View_DepthOfFieldFocalLength, UniformBufferConstants_View.View_DepthOfFieldFocalRegion, UniformBufferConstants_View.View_DepthOfFieldNearTransitionRegion, UniformBufferConstants_View.View_DepthOfFieldFarTransitionRegion, UniformBufferConstants_View.View_MotionBlurNormalizedToPixel, UniformBufferConstants_View.View_GeneralPurposeTweak, UniformBufferConstants_View.View_GeneralPurposeTweak2, UniformBufferConstants_View.View_DemosaicVposOffset, UniformBufferConstants_View.View_DecalDepthBias, UniformBufferConstants_View.View_IndirectLightingColorScale, UniformBufferConstants_View.View_PrecomputedIndirectLightingColorScale, UniformBufferConstants_View.View_PrecomputedIndirectSpecularColorScale, vec4[](UniformBufferConstants_View.View_AtmosphereLightDirection[0], UniformBufferConstants_View.View_AtmosphereLightDirection[1]), vec4[](UniformBufferConstants_View.View_AtmosphereLightIlluminanceOnGroundPostTransmittance[0], UniformBufferConstants_View.View_AtmosphereLightIlluminanceOnGroundPostTransmittance[1]), vec4[](UniformBufferConstants_View.View_AtmosphereLightIlluminanceOuterSpace[0], UniformBufferConstants_View.View_AtmosphereLightIlluminanceOuterSpace[1]), vec4[](UniformBufferConstants_View.View_AtmosphereLightDiscLuminance[0], UniformBufferConstants_View.View_AtmosphereLightDiscLuminance[1]), vec4[](UniformBufferConstants_View.View_AtmosphereLightDiscCosHalfApexAngle_PPTrans[0], UniformBufferConstants_View.View_AtmosphereLightDiscCosHalfApexAngle_PPTrans[1]), UniformBufferConstants_View.View_SkyViewLutSizeAndInvSize, UniformBufferConstants_View.View_SkyCameraTranslatedWorldOrigin, UniformBufferConstants_View.View_SkyPlanetTranslatedWorldCenterAndViewHeight, UniformBufferConstants_View.View_SkyViewLutReferential, UniformBufferConstants_View.View_SkyAtmosphereSkyLuminanceFactor, UniformBufferConstants_View.View_SkyAtmospherePresentInScene, UniformBufferConstants_View.View_SkyAtmosphereHeightFogContribution, UniformBufferConstants_View.View_SkyAtmosphereBottomRadiusKm, UniformBufferConstants_View.View_SkyAtmosphereTopRadiusKm, UniformBufferConstants_View.View_SkyAtmosphereCameraAerialPerspectiveVolumeSizeAndInvSize, UniformBufferConstants_View.View_SkyAtmosphereAerialPerspectiveStartDepthKm, UniformBufferConstants_View.View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolution, UniformBufferConstants_View.View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthResolutionInv, UniformBufferConstants_View.View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKm, UniformBufferConstants_View.View_SkyAtmosphereCameraAerialPerspectiveVolumeDepthSliceLengthKmInv, UniformBufferConstants_View.View_SkyAtmosphereApplyCameraAerialPerspectiveVolume, UniformBufferConstants_View.View_NormalCurvatureToRoughnessScaleBias, UniformBufferConstants_View.View_RenderingReflectionCaptureMask, UniformBufferConstants_View.View_RealTimeReflectionCapture, UniformBufferConstants_View.View_RealTimeReflectionCapturePreExposure, UniformBufferConstants_View.View_AmbientCubemapTint, UniformBufferConstants_View.View_AmbientCubemapIntensity, UniformBufferConstants_View.View_SkyLightApplyPrecomputedBentNormalShadowingFlag, UniformBufferConstants_View.View_SkyLightAffectReflectionFlag, UniformBufferConstants_View.View_SkyLightAffectGlobalIlluminationFlag, UniformBufferConstants_View.View_SkyLightColor, vec4[](UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[0], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[1], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[2], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[3], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[4], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[5], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[6], UniformBufferConstants_View.View_MobileSkyIrradianceEnvironmentMap[7]), UniformBufferConstants_View.View_MobilePreviewMode, UniformBufferConstants_View.View_HMDEyePaddingOffset, UniformBufferConstants_View.View_ReflectionCubemapMaxMip, UniformBufferConstants_View.View_ShowDecalsMask, UniformBufferConstants_View.View_DistanceFieldAOSpecularOcclusionMode, UniformBufferConstants_View.View_IndirectCapsuleSelfShadowingIntensity, UniformBufferConstants_View.View_ReflectionEnvironmentRoughnessMixingScaleBiasAndLargestWeight, UniformBufferConstants_View.View_StereoPassIndex, vec4[](UniformBufferConstants_View.View_GlobalVolumeTranslatedCenterAndExtent[0], UniformBufferConstants_View.View_GlobalVolumeTranslatedCenterAndExtent[1], UniformBufferConstants_View.View_GlobalVolumeTranslatedCenterAndExtent[2], UniformBufferConstants_View.View_GlobalVolumeTranslatedCenterAndExtent[3], UniformBufferConstants_View.View_GlobalVolumeTranslatedCenterAndExtent[4], UniformBufferConstants_View.View_GlobalVolumeTranslatedCenterAndExtent[5]), vec4[](UniformBufferConstants_View.View_GlobalVolumeTranslatedWorldToUVAddAndMul[0], UniformBufferConstants_View.View_GlobalVolumeTranslatedWorldToUVAddAndMul[1], UniformBufferConstants_View.View_GlobalVolumeTranslatedWorldToUVAddAndMul[2], UniformBufferConstants_View.View_GlobalVolumeTranslatedWorldToUVAddAndMul[3], UniformBufferConstants_View.View_GlobalVolumeTranslatedWorldToUVAddAndMul[4], UniformBufferConstants_View.View_GlobalVolumeTranslatedWorldToUVAddAndMul[5]), vec4[](UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVScale[0], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVScale[1], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVScale[2], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVScale[3], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVScale[4], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVScale[5]), vec4[](UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVBias[0], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVBias[1], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVBias[2], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVBias[3], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVBias[4], UniformBufferConstants_View.View_GlobalDistanceFieldMipTranslatedWorldToUVBias[5]), UniformBufferConstants_View.View_GlobalDistanceFieldMipFactor, UniformBufferConstants_View.View_GlobalDistanceFieldMipTransition, UniformBufferConstants_View.View_GlobalDistanceFieldClipmapSizeInPages, UniformBufferConstants_View.View_GlobalDistanceFieldInvPageAtlasSize, UniformBufferConstants_View.View_GlobalDistanceFieldInvCoverageAtlasSize, UniformBufferConstants_View.View_GlobalVolumeDimension, UniformBufferConstants_View.View_GlobalVolumeTexelSize, UniformBufferConstants_View.View_MaxGlobalDFAOConeDistance, UniformBufferConstants_View.View_NumGlobalSDFClipmaps, UniformBufferConstants_View.View_CoveredExpandSurfaceScale, UniformBufferConstants_View.View_NotCoveredExpandSurfaceScale, UniformBufferConstants_View.View_NotCoveredMinStepScale, UniformBufferConstants_View.View_DitheredTransparencyStepThreshold, UniformBufferConstants_View.View_DitheredTransparencyTraceThreshold, UniformBufferConstants_View.View_CursorPosition, UniformBufferConstants_View.View_bCheckerboardSubsurfaceProfileRendering, UniformBufferConstants_View.View_VolumetricFogInvGridSize, UniformBufferConstants_View.View_VolumetricFogGridZParams, UniformBufferConstants_View.View_VolumetricFogSVPosToVolumeUV, UniformBufferConstants_View.View_VolumetricFogViewGridUVToPrevViewRectUV, UniformBufferConstants_View.View_VolumetricFogPrevViewGridRectUVToResourceUV, UniformBufferConstants_View.View_VolumetricFogPrevUVMax, UniformBufferConstants_View.View_VolumetricFogScreenToResourceUV, UniformBufferConstants_View.View_VolumetricFogUVMax, UniformBufferConstants_View.View_VolumetricFogMaxDistance, UniformBufferConstants_View.View_VolumetricLightmapWorldToUVScale, UniformBufferConstants_View.View_VolumetricLightmapWorldToUVAdd, UniformBufferConstants_View.View_VolumetricLightmapIndirectionTextureSize, UniformBufferConstants_View.View_VolumetricLightmapBrickSize, UniformBufferConstants_View.View_VolumetricLightmapBrickTexelSize, UniformBufferConstants_View.View_IndirectLightingCacheShowFlag, UniformBufferConstants_View.View_EyeToPixelSpreadAngle, vec4[](UniformBufferConstants_View.View_XRPassthroughCameraUVs[0], UniformBufferConstants_View.View_XRPassthroughCameraUVs[1]), UniformBufferConstants_View.View_GlobalVirtualTextureMipBias, UniformBufferConstants_View.View_VirtualTextureFeedbackShift, UniformBufferConstants_View.View_VirtualTextureFeedbackMask, UniformBufferConstants_View.View_VirtualTextureFeedbackStride, UniformBufferConstants_View.View_VirtualTextureFeedbackJitterOffset, UniformBufferConstants_View.View_VirtualTextureFeedbackSampleOffset, UniformBufferConstants_View.View_RuntimeVirtualTextureMipLevel, UniformBufferConstants_View.View_RuntimeVirtualTexturePackHeight, UniformBufferConstants_View.View_RuntimeVirtualTextureDebugParams, UniformBufferConstants_View.View_OverrideLandscapeLOD, UniformBufferConstants_View.View_FarShadowStaticMeshLODBias, UniformBufferConstants_View.View_MinRoughness, UniformBufferConstants_View.View_HairRenderInfo, UniformBufferConstants_View.View_EnableSkyLight, UniformBufferConstants_View.View_HairRenderInfoBits, UniformBufferConstants_View.View_HairComponents, UniformBufferConstants_View.View_bSubsurfacePostprocessEnabled, UniformBufferConstants_View.View_SSProfilesTextureSizeAndInvSize, UniformBufferConstants_View.View_SSProfilesPreIntegratedTextureSizeAndInvSize, UniformBufferConstants_View.View_SpecularProfileTextureSizeAndInvSize, UniformBufferConstants_View.View_PhysicsFieldClipmapCenter, UniformBufferConstants_View.View_PhysicsFieldClipmapDistance, UniformBufferConstants_View.View_PhysicsFieldClipmapResolution, UniformBufferConstants_View.View_PhysicsFieldClipmapExponent, UniformBufferConstants_View.View_PhysicsFieldClipmapCount, UniformBufferConstants_View.View_PhysicsFieldTargetCount, ivec4[](UniformBufferConstants_View.View_PhysicsFieldTargets[0], UniformBufferConstants_View.View_PhysicsFieldTargets[1], UniformBufferConstants_View.View_PhysicsFieldTargets[2], UniformBufferConstants_View.View_PhysicsFieldTargets[3], UniformBufferConstants_View.View_PhysicsFieldTargets[4], UniformBufferConstants_View.View_PhysicsFieldTargets[5], UniformBufferConstants_View.View_PhysicsFieldTargets[6], UniformBufferConstants_View.View_PhysicsFieldTargets[7], UniformBufferConstants_View.View_PhysicsFieldTargets[8], UniformBufferConstants_View.View_PhysicsFieldTargets[9], UniformBufferConstants_View.View_PhysicsFieldTargets[10], UniformBufferConstants_View.View_PhysicsFieldTargets[11], UniformBufferConstants_View.View_PhysicsFieldTargets[12], UniformBufferConstants_View.View_PhysicsFieldTargets[13], UniformBufferConstants_View.View_PhysicsFieldTargets[14], UniformBufferConstants_View.View_PhysicsFieldTargets[15], UniformBufferConstants_View.View_PhysicsFieldTargets[16], UniformBufferConstants_View.View_PhysicsFieldTargets[17], UniformBufferConstants_View.View_PhysicsFieldTargets[18], UniformBufferConstants_View.View_PhysicsFieldTargets[19], UniformBufferConstants_View.View_PhysicsFieldTargets[20], UniformBufferConstants_View.View_PhysicsFieldTargets[21], UniformBufferConstants_View.View_PhysicsFieldTargets[22], UniformBufferConstants_View.View_PhysicsFieldTargets[23], UniformBufferConstants_View.View_PhysicsFieldTargets[24], UniformBufferConstants_View.View_PhysicsFieldTargets[25], UniformBufferConstants_View.View_PhysicsFieldTargets[26], UniformBufferConstants_View.View_PhysicsFieldTargets[27], UniformBufferConstants_View.View_PhysicsFieldTargets[28], UniformBufferConstants_View.View_PhysicsFieldTargets[29], UniformBufferConstants_View.View_PhysicsFieldTargets[30], UniformBufferConstants_View.View_PhysicsFieldTargets[31]), UniformBufferConstants_View.View_GPUSceneViewId, UniformBufferConstants_View.View_ViewResolutionFraction, UniformBufferConstants_View.View_SubSurfaceColorAsTransmittanceAtDistanceInMeters, UniformBufferConstants_View.View_TanAndInvTanHalfFOV, UniformBufferConstants_View.View_PrevTanAndInvTanHalfFOV, UniformBufferConstants_View.View_GlintLUTParameters0, UniformBufferConstants_View.View_GlintLUTParameters1, UniformBufferConstants_View.View_bShadingEnergyConservation, UniformBufferConstants_View.View_bShadingEnergyPreservation, UniformBufferConstants_View.View_RectLightAtlasSizeAndInvSize, UniformBufferConstants_View.View_RectLightAtlasMaxMipLevel, UniformBufferConstants_View.View_IESAtlasSizeAndInvSize, UniformBufferConstants_View.View_TLASRelativePreViewTranslation, UniformBufferConstants_View.View_TLASViewTilePosition);
    uvec2 _895 = uvec2(vec2(gl_GlobalInvocationID.xy) + View.ViewRectMin.xy);
    if ((uint(View.ViewSizeAndInvSize.x) > gl_GlobalInvocationID.x) && (uint(View.ViewSizeAndInvSize.y) > gl_GlobalInvocationID.y))
    {
        vec2 _904 = vec2(_895) + vec2(0.5);
        vec2 _910 = _904 / (View.ViewSizeAndInvSize.xy + View.ViewRectMin.xy);
        float _913 = (2.0 * _910.x) - 1.0;
        float _916 = 1.0 - (2.0 * _910.y);
        vec4 _919 = texelFetch(SPIRV_Cross_CombinedGBufferBSPIRV_Cross_DummySampler, ivec2(_895), int(0u));
        vec4 _929 = texelFetch(SPIRV_Cross_CombinedInputDepthSPIRV_Cross_DummySampler, ivec2(_895), int(0u));
        float _930 = _929.x;
        bool _933 = _RootShaderParameters.CustomStencilShift != 0u;
        uint _940 = _RootShaderParameters.CustomStencilShift & 31u;
        float _950 = float(_933 ? ((texelFetch(SPIRV_Cross_CombinedCustomStencilSPIRV_Cross_DummySampler, ivec2(_895), int(0u)).y & _RootShaderParameters.CustomStencilMask) >> _940) : (texelFetch(SPIRV_Cross_CombinedCustomStencilSPIRV_Cross_DummySampler, ivec2(_895), int(0u)).y & _RootShaderParameters.CustomStencilMask)) / float(_933 ? (_RootShaderParameters.CustomStencilMask >> _940) : _RootShaderParameters.CustomStencilMask);
        bool _961 = (texelFetch(SPIRV_Cross_CombinedStencilTextureSPIRV_Cross_DummySampler, ivec2(_895), int(0u)).y & 8u) != 0u;
        vec2 _974 = _904 / (View.BufferSizeAndInvSize.xy + View.ViewRectMin.xy);
        vec4 _978 = textureLod(SPIRV_Cross_CombinedReflectionTextureSampler, _974, 0.0);
        vec4 _981 = textureLod(SPIRV_Cross_CombinedInputSeparateTranslucencySampler, _974, 0.0);
        float _986 = 1.0 - textureLod(SPIRV_Cross_CombinedDBufferASampler, _974, 0.0).w;
        vec2 _1032;
        if (_RootShaderParameters.LumenSpecularCurrentFrame == 0u)
        {
            vec4 _999 = texelFetch(SPIRV_Cross_CombinedInputVelocitySPIRV_Cross_DummySampler, ivec2(_895), int(0u));
            vec4 _1005 = View.ClipToPrevClip * vec4(_913, _916, _930, 1.0);
            vec2 _1023;
            if (_999.x > 0.0)
            {
                vec2 _1018 = ((_999.xy * 4.008016109466552734375) - vec2(2.0039775371551513671875)).xy;
                _1023 = ((_1018 * abs(_1018)) * 0.5).xy;
            }
            else
            {
                _1023 = vec3(_913, _916, _930).xy - (_1005.xy / vec2(_1005.w));
            }
            vec2 _1024 = vec2(_913, _916) - _1023;
            _1032 = vec2(0.5 + (0.5 * _1024.x), 0.5 - (0.5 * _1024.y));
        }
        else
        {
            _1032 = _974;
        }
        float _1036 = _919.z;
        uint _1041 = uint(round(_919.w * 255.0)) & 15u;
        int _1042 = int(_1041);
        vec4 _1059 = mix(vec4(0.0), texelFetch(SPIRV_Cross_CombinedGBufferDSPIRV_Cross_DummySampler, ivec2(_895), int(0u)), bvec4((((((((_1042 == 2) || (_1042 == 3)) || (_1042 == 4)) || (_1042 == 5)) || (_1042 == 6)) || (_1042 == 7)) || (_1042 == 8)) || (_1042 == 9)));
        float _1069;
        if (_1041 == 4u)
        {
            _1069 = mix(_1036, _1059.y, _1059.x);
        }
        else
        {
            _1069 = (_1041 == 0u) ? 1.0 : _1036;
        }
        float _1080;
        if (_1041 == _RootShaderParameters.ReactiveShadingModelID)
        {
            _1080 = (_RootShaderParameters.ForceLitReactiveValue > 0.0) ? _RootShaderParameters.ForceLitReactiveValue : _1059.x;
        }
        else
        {
            _1080 = 0.0;
        }
        vec4 _1082 = abs(clamp(texelFetch(SPIRV_Cross_CombinedSceneColorSPIRV_Cross_DummySampler, ivec2(_895), int(0u)), vec4(0.0), vec4(1.0)) - clamp(texelFetch(SPIRV_Cross_CombinedSceneColorPreAlphaSPIRV_Cross_DummySampler, ivec2(_895), int(0u)), vec4(0.0), vec4(1.0)));
        vec3 _1083 = _1082.xyz;
        float _1100 = min(_981.w, 1.0 - (clamp((_RootShaderParameters.ReactiveMaskPreDOFTranslucencyMax != 0u) ? max(_1082.x, max(_1082.y, _1082.z)) : length(_1083), 0.0, 1.0) * _RootShaderParameters.ReactiveMaskPreDOFTranslucencyScale));
        vec4 _1110 = View.SVPositionToTranslatedWorld * vec4(float(_895.x), float(_895.y), _930, 1.0);
        float _1115 = length(_1110.xyz / vec3(_1110.w));
        float _1123 = 1.0 - _1100;
        float _1131 = clamp(dot(max(_981.xyz, _1083).xyz, vec3(0.300000011920928955078125, 0.589999973773956298828125, 0.10999999940395355224609375)), 0.0, 1.0);
        vec2 _1135 = _338;
        _1135.x = (_1123 * _RootShaderParameters.ReactiveMaskTranslucencyBias) + ((_RootShaderParameters.ReactiveMaskTranslucencyLumaBias * _1131) * _1100);
        vec2 _1144 = _1135;
        _1144.y = (_1123 * _RootShaderParameters.ReactiveHistoryTranslucencyBias) + ((_RootShaderParameters.ReactiveHistoryTranslucencyLumaBias * _1131) * _1100);
        vec2 _1153 = mix(_1144, mix(_1144, vec2(0.0), vec2(clamp(_1115 / _RootShaderParameters.ReactiveMaskTranslucencyMaxDistance, 0.0, 1.0))), bvec2(_RootShaderParameters.ReactiveMaskTranslucencyMaxDistance > 0.0));
        float _1154 = 1.0 - ((_RootShaderParameters.FurthestReflectionCaptureDistance > 0.0) ? mix(_1069, 1.0, clamp(_1115 / _RootShaderParameters.FurthestReflectionCaptureDistance, 0.0, 1.0)) : _1069);
        float _1158 = clamp(_1154 * _RootShaderParameters.ReactiveMaskRoughnessScale, 0.0, 1.0);
        float _1159 = _978.w;
        bool _1163 = _RootShaderParameters.ReactiveMaskReflectionScale > 0.0;
        float _1199;
        if ((_1159 > 0.0) && _1163)
        {
            float _1174 = mix(_1159 * _RootShaderParameters.ReactiveMaskReflectionScale, 1.0, dot(_978.xyz, vec3(0.300000011920928955078125, 0.589999973773956298828125, 0.10999999940395355224609375)) * _RootShaderParameters.ReactiveMaskReflectionLumaBias);
            _1199 = _1174 + (max(_1158 - _1174, 0.0) * _RootShaderParameters.ReactiveMaskRoughnessBias);
        }
        else
        {
            vec3 _1181 = textureLod(SPIRV_Cross_CombinedLumenSpecularSampler, _1032, 0.0).xyz;
            float _1198;
            if (any(notEqual(_1181, vec3(0.0))) && _1163)
            {
                float _1191 = (clamp(dot(_1181, vec3(0.300000011920928955078125, 0.589999973773956298828125, 0.10999999940395355224609375)), 0.0, 1.0) * _RootShaderParameters.ReactiveMaskReflectionScale) * _1154;
                _1198 = _1191 + (max(_1158 - _1191, 0.0) * _RootShaderParameters.ReactiveMaskRoughnessBias);
            }
            else
            {
                _1198 = _1158;
            }
            _1199 = _1198;
        }
        imageStore(CompositeMask, ivec2(gl_GlobalInvocationID.xy), vec4(max(max(max(clamp(_1153.x + _1199, 0.0, 1.0), _950 * _RootShaderParameters.CustomStencilReactiveMaskScale), _986 * _RootShaderParameters.DeferredDecalReactiveMaskScale), _961 ? _RootShaderParameters.ReactiveMaskTAAResponsiveValue : 0.0)));
        imageStore(ReactiveMask, ivec2(gl_GlobalInvocationID.xy), vec4(max(max(max(max(_1080, mix(0.0, 1.0, _1153.y)), _950 * _RootShaderParameters.CustomStencilReactiveHistoryScale), _961 ? _RootShaderParameters.ReactiveHistoryTAAResponsiveValue : 0.0), _986 * _RootShaderParameters.DeferredDecalReactiveHistoryScale)));
    }
}

